Class {
	#name : 'SSLConstantsKdf',
	#superclass : 'SharedPool',
	#classVars : [
		'EVP_KDF_HKDF_MODE_EXPAND_ONLY',
		'EVP_KDF_HKDF_MODE_EXTRACT_AND_EXPAND',
		'EVP_KDF_HKDF_MODE_EXTRACT_ONLY',
		'EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_CLI_TO_SRV',
		'EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_SRV_TO_CLI',
		'EVP_KDF_SSHKDF_TYPE_INITIAL_IV_CLI_TO_SRV',
		'EVP_KDF_SSHKDF_TYPE_INITIAL_IV_SRV_TO_CLI',
		'EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_CLI_TO_SRV',
		'EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_SRV_TO_CLI',
		'EVP_PKEY_CTRL_HKDF_INFO',
		'EVP_PKEY_CTRL_HKDF_KEY',
		'EVP_PKEY_CTRL_HKDF_MD',
		'EVP_PKEY_CTRL_HKDF_MODE',
		'EVP_PKEY_CTRL_HKDF_SALT',
		'EVP_PKEY_CTRL_PASS',
		'EVP_PKEY_CTRL_SCRYPT_MAXMEM_BYTES',
		'EVP_PKEY_CTRL_SCRYPT_N',
		'EVP_PKEY_CTRL_SCRYPT_P',
		'EVP_PKEY_CTRL_SCRYPT_R',
		'EVP_PKEY_CTRL_SCRYPT_SALT',
		'EVP_PKEY_CTRL_TLS_MD',
		'EVP_PKEY_CTRL_TLS_SECRET',
		'EVP_PKEY_CTRL_TLS_SEED',
		'EVP_PKEY_HKDEF_MODE_EXPAND_ONLY',
		'EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND',
		'EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_HKDF_MODE_EXPAND_ONLY [

	^ EVP_KDF_HKDF_MODE_EXPAND_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_HKDF_MODE_EXTRACT_AND_EXPAND [

	^ EVP_KDF_HKDF_MODE_EXTRACT_AND_EXPAND
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_HKDF_MODE_EXTRACT_ONLY [

	^ EVP_KDF_HKDF_MODE_EXTRACT_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_CLI_TO_SRV [

	^ EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_CLI_TO_SRV
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_SRV_TO_CLI [

	^ EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_SRV_TO_CLI
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_INITIAL_IV_CLI_TO_SRV [

	^ EVP_KDF_SSHKDF_TYPE_INITIAL_IV_CLI_TO_SRV
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_INITIAL_IV_SRV_TO_CLI [

	^ EVP_KDF_SSHKDF_TYPE_INITIAL_IV_SRV_TO_CLI
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_CLI_TO_SRV [

	^ EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_CLI_TO_SRV
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_SRV_TO_CLI [

	^ EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_SRV_TO_CLI
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_HKDF_INFO [

	^ EVP_PKEY_CTRL_HKDF_INFO
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_HKDF_KEY [

	^ EVP_PKEY_CTRL_HKDF_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_HKDF_MD [

	^ EVP_PKEY_CTRL_HKDF_MD
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_HKDF_MODE [

	^ EVP_PKEY_CTRL_HKDF_MODE
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_HKDF_SALT [

	^ EVP_PKEY_CTRL_HKDF_SALT
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_PASS [

	^ EVP_PKEY_CTRL_PASS
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_SCRYPT_MAXMEM_BYTES [

	^ EVP_PKEY_CTRL_SCRYPT_MAXMEM_BYTES
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_SCRYPT_N [

	^ EVP_PKEY_CTRL_SCRYPT_N
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_SCRYPT_P [

	^ EVP_PKEY_CTRL_SCRYPT_P
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_SCRYPT_R [

	^ EVP_PKEY_CTRL_SCRYPT_R
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_SCRYPT_SALT [

	^ EVP_PKEY_CTRL_SCRYPT_SALT
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_TLS_MD [

	^ EVP_PKEY_CTRL_TLS_MD
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_TLS_SECRET [

	^ EVP_PKEY_CTRL_TLS_SECRET
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_CTRL_TLS_SEED [

	^ EVP_PKEY_CTRL_TLS_SEED
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_HKDEF_MODE_EXPAND_ONLY [

	^ EVP_PKEY_HKDEF_MODE_EXPAND_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND [

	^ EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND
]

{ #category : 'accessing - constants' }
SSLConstantsKdf class >> EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY [

	^ EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY
]

{ #category : 'class initialization' }
SSLConstantsKdf class >> initialize [

	EVP_KDF_HKDF_MODE_EXTRACT_AND_EXPAND := 0.
	EVP_KDF_HKDF_MODE_EXTRACT_ONLY := 1.
	EVP_KDF_HKDF_MODE_EXPAND_ONLY := 2.
	EVP_KDF_SSHKDF_TYPE_INITIAL_IV_CLI_TO_SRV := 16r41.
	EVP_KDF_SSHKDF_TYPE_INITIAL_IV_SRV_TO_CLI := 16r42.
	EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_CLI_TO_SRV := 16r43.
	EVP_KDF_SSHKDF_TYPE_ENCRYPTION_KEY_SRV_TO_CLI := 16r44.
	EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_CLI_TO_SRV := 16r45.
	EVP_KDF_SSHKDF_TYPE_INTEGRITY_KEY_SRV_TO_CLI := 16r46.
	EVP_PKEY_CTRL_TLS_MD := 16r1000	 "(EVP_PKEY_ALG_CTRL)".
	EVP_PKEY_CTRL_TLS_SECRET := 16r1001	 "(EVP_PKEY_ALG_CTRL + 1)".
	EVP_PKEY_CTRL_TLS_SEED := 16r1002	 "(EVP_PKEY_ALG_CTRL + 2)".
	EVP_PKEY_CTRL_HKDF_MD := 16r1003	 "(EVP_PKEY_ALG_CTRL + 3)".
	EVP_PKEY_CTRL_HKDF_SALT := 16r1004	 "(EVP_PKEY_ALG_CTRL + 4)".
	EVP_PKEY_CTRL_HKDF_KEY := 16r1005	 "(EVP_PKEY_ALG_CTRL + 5)".
	EVP_PKEY_CTRL_HKDF_INFO := 16r1006	 "(EVP_PKEY_ALG_CTRL + 6)".
	EVP_PKEY_CTRL_HKDF_MODE := 16r1007	 "(EVP_PKEY_ALG_CTRL + 7)".
	EVP_PKEY_CTRL_PASS := 16r1008	 "(EVP_PKEY_ALG_CTRL + 8)".
	EVP_PKEY_CTRL_SCRYPT_SALT := 16r1009	 "(EVP_PKEY_ALG_CTRL + 9)".
	EVP_PKEY_CTRL_SCRYPT_N := 16r100A	 "(EVP_PKEY_ALG_CTRL + 10)".
	EVP_PKEY_CTRL_SCRYPT_R := 16r100B	 "(EVP_PKEY_ALG_CTRL + 11)".
	EVP_PKEY_CTRL_SCRYPT_P := 16r100C	 "(EVP_PKEY_ALG_CTRL + 12)".
	EVP_PKEY_CTRL_SCRYPT_MAXMEM_BYTES := 16r100D	 "(EVP_PKEY_ALG_CTRL + 13)".
	EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND := 0	 "\
            EVP_KDF_HKDF_MODE_EXTRACT_AND_EXPAND".
	EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY := 1	 "\
            EVP_KDF_HKDF_MODE_EXTRACT_ONLY".
	EVP_PKEY_HKDEF_MODE_EXPAND_ONLY := 2	 "\
            EVP_KDF_HKDF_MODE_EXPAND_ONLY"
]
