Class {
	#name : 'SSLConstantsRanderr',
	#superclass : 'SharedPool',
	#classVars : [
		'RAND_R_ADDITIONAL_INPUT_TOO_LONG',
		'RAND_R_ALREADY_INSTANTIATED',
		'RAND_R_ARGUMENT_OUT_OF_RANGE',
		'RAND_R_CANNOT_OPEN_FILE',
		'RAND_R_DRBG_ALREADY_INITIALIZED',
		'RAND_R_DRBG_NOT_INITIALISED',
		'RAND_R_ENTROPY_INPUT_TOO_LONG',
		'RAND_R_ENTROPY_OUT_OF_RANGE',
		'RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED',
		'RAND_R_ERROR_INITIALISING_DRBG',
		'RAND_R_ERROR_INSTANTIATING_DRBG',
		'RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT',
		'RAND_R_ERROR_RETRIEVING_ENTROPY',
		'RAND_R_ERROR_RETRIEVING_NONCE',
		'RAND_R_FAILED_TO_CREATE_LOCK',
		'RAND_R_FUNC_NOT_IMPLEMENTED',
		'RAND_R_FWRITE_ERROR',
		'RAND_R_GENERATE_ERROR',
		'RAND_R_INSUFFICIENT_DRBG_STRENGTH',
		'RAND_R_INTERNAL_ERROR',
		'RAND_R_INVALID_PROPERTY_QUERY',
		'RAND_R_IN_ERROR_STATE',
		'RAND_R_NOT_A_REGULAR_FILE',
		'RAND_R_NOT_INSTANTIATED',
		'RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED',
		'RAND_R_PARENT_LOCKING_NOT_ENABLED',
		'RAND_R_PARENT_STRENGTH_TOO_WEAK',
		'RAND_R_PERSONALISATION_STRING_TOO_LONG',
		'RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED',
		'RAND_R_PRNG_NOT_SEEDED',
		'RAND_R_RANDOM_POOL_IS_EMPTY',
		'RAND_R_RANDOM_POOL_OVERFLOW',
		'RAND_R_RANDOM_POOL_UNDERFLOW',
		'RAND_R_REQUEST_TOO_LARGE_FOR_DRBG',
		'RAND_R_RESEED_ERROR',
		'RAND_R_SELFTEST_FAILURE',
		'RAND_R_TOO_LITTLE_NONCE_REQUESTED',
		'RAND_R_TOO_MUCH_NONCE_REQUESTED',
		'RAND_R_UNABLE_TO_CREATE_DRBG',
		'RAND_R_UNABLE_TO_FETCH_DRBG',
		'RAND_R_UNABLE_TO_GET_PARENT_RESEED_PROP_COUNTER',
		'RAND_R_UNABLE_TO_GET_PARENT_STRENGTH',
		'RAND_R_UNABLE_TO_LOCK_PARENT',
		'RAND_R_UNSUPPORTED_DRBG_FLAGS',
		'RAND_R_UNSUPPORTED_DRBG_TYPE'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ADDITIONAL_INPUT_TOO_LONG [

	^ RAND_R_ADDITIONAL_INPUT_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ALREADY_INSTANTIATED [

	^ RAND_R_ALREADY_INSTANTIATED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ARGUMENT_OUT_OF_RANGE [

	^ RAND_R_ARGUMENT_OUT_OF_RANGE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_CANNOT_OPEN_FILE [

	^ RAND_R_CANNOT_OPEN_FILE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_DRBG_ALREADY_INITIALIZED [

	^ RAND_R_DRBG_ALREADY_INITIALIZED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_DRBG_NOT_INITIALISED [

	^ RAND_R_DRBG_NOT_INITIALISED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ENTROPY_INPUT_TOO_LONG [

	^ RAND_R_ENTROPY_INPUT_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ENTROPY_OUT_OF_RANGE [

	^ RAND_R_ENTROPY_OUT_OF_RANGE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED [

	^ RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_INITIALISING_DRBG [

	^ RAND_R_ERROR_INITIALISING_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_INSTANTIATING_DRBG [

	^ RAND_R_ERROR_INSTANTIATING_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT [

	^ RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_RETRIEVING_ENTROPY [

	^ RAND_R_ERROR_RETRIEVING_ENTROPY
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_ERROR_RETRIEVING_NONCE [

	^ RAND_R_ERROR_RETRIEVING_NONCE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_FAILED_TO_CREATE_LOCK [

	^ RAND_R_FAILED_TO_CREATE_LOCK
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_FUNC_NOT_IMPLEMENTED [

	^ RAND_R_FUNC_NOT_IMPLEMENTED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_FWRITE_ERROR [

	^ RAND_R_FWRITE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_GENERATE_ERROR [

	^ RAND_R_GENERATE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_INSUFFICIENT_DRBG_STRENGTH [

	^ RAND_R_INSUFFICIENT_DRBG_STRENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_INTERNAL_ERROR [

	^ RAND_R_INTERNAL_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_INVALID_PROPERTY_QUERY [

	^ RAND_R_INVALID_PROPERTY_QUERY
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_IN_ERROR_STATE [

	^ RAND_R_IN_ERROR_STATE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_NOT_A_REGULAR_FILE [

	^ RAND_R_NOT_A_REGULAR_FILE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_NOT_INSTANTIATED [

	^ RAND_R_NOT_INSTANTIATED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED [

	^ RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_PARENT_LOCKING_NOT_ENABLED [

	^ RAND_R_PARENT_LOCKING_NOT_ENABLED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_PARENT_STRENGTH_TOO_WEAK [

	^ RAND_R_PARENT_STRENGTH_TOO_WEAK
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_PERSONALISATION_STRING_TOO_LONG [

	^ RAND_R_PERSONALISATION_STRING_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED [

	^ RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_PRNG_NOT_SEEDED [

	^ RAND_R_PRNG_NOT_SEEDED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_RANDOM_POOL_IS_EMPTY [

	^ RAND_R_RANDOM_POOL_IS_EMPTY
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_RANDOM_POOL_OVERFLOW [

	^ RAND_R_RANDOM_POOL_OVERFLOW
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_RANDOM_POOL_UNDERFLOW [

	^ RAND_R_RANDOM_POOL_UNDERFLOW
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_REQUEST_TOO_LARGE_FOR_DRBG [

	^ RAND_R_REQUEST_TOO_LARGE_FOR_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_RESEED_ERROR [

	^ RAND_R_RESEED_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_SELFTEST_FAILURE [

	^ RAND_R_SELFTEST_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_TOO_LITTLE_NONCE_REQUESTED [

	^ RAND_R_TOO_LITTLE_NONCE_REQUESTED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_TOO_MUCH_NONCE_REQUESTED [

	^ RAND_R_TOO_MUCH_NONCE_REQUESTED
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNABLE_TO_CREATE_DRBG [

	^ RAND_R_UNABLE_TO_CREATE_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNABLE_TO_FETCH_DRBG [

	^ RAND_R_UNABLE_TO_FETCH_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNABLE_TO_GET_PARENT_RESEED_PROP_COUNTER [

	^ RAND_R_UNABLE_TO_GET_PARENT_RESEED_PROP_COUNTER
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNABLE_TO_GET_PARENT_STRENGTH [

	^ RAND_R_UNABLE_TO_GET_PARENT_STRENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNABLE_TO_LOCK_PARENT [

	^ RAND_R_UNABLE_TO_LOCK_PARENT
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNSUPPORTED_DRBG_FLAGS [

	^ RAND_R_UNSUPPORTED_DRBG_FLAGS
]

{ #category : 'accessing - constants' }
SSLConstantsRanderr class >> RAND_R_UNSUPPORTED_DRBG_TYPE [

	^ RAND_R_UNSUPPORTED_DRBG_TYPE
]

{ #category : 'class initialization' }
SSLConstantsRanderr class >> initialize [

	RAND_R_ADDITIONAL_INPUT_TOO_LONG := 16r66.
	RAND_R_ALREADY_INSTANTIATED := 16r67.
	RAND_R_ARGUMENT_OUT_OF_RANGE := 16r69.
	RAND_R_CANNOT_OPEN_FILE := 16r79.
	RAND_R_DRBG_ALREADY_INITIALIZED := 16r81.
	RAND_R_DRBG_NOT_INITIALISED := 16r68.
	RAND_R_ENTROPY_INPUT_TOO_LONG := 16r6A.
	RAND_R_ENTROPY_OUT_OF_RANGE := 16r7C.
	RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED := 16r7F.
	RAND_R_ERROR_INITIALISING_DRBG := 16r6B.
	RAND_R_ERROR_INSTANTIATING_DRBG := 16r6C.
	RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT := 16r6D.
	RAND_R_ERROR_RETRIEVING_ENTROPY := 16r6E.
	RAND_R_ERROR_RETRIEVING_NONCE := 16r6F.
	RAND_R_FAILED_TO_CREATE_LOCK := 16r7E.
	RAND_R_FUNC_NOT_IMPLEMENTED := 16r65.
	RAND_R_FWRITE_ERROR := 16r7B.
	RAND_R_GENERATE_ERROR := 16r70.
	RAND_R_INSUFFICIENT_DRBG_STRENGTH := 16r8B.
	RAND_R_INTERNAL_ERROR := 16r71.
	RAND_R_INVALID_PROPERTY_QUERY := 16r89.
	RAND_R_IN_ERROR_STATE := 16r72.
	RAND_R_NOT_A_REGULAR_FILE := 16r7A.
	RAND_R_NOT_INSTANTIATED := 16r73.
	RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED := 16r80.
	RAND_R_PARENT_LOCKING_NOT_ENABLED := 16r82.
	RAND_R_PARENT_STRENGTH_TOO_WEAK := 16r83.
	RAND_R_PERSONALISATION_STRING_TOO_LONG := 16r74.
	RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED := 16r85.
	RAND_R_PRNG_NOT_SEEDED := 16r64.
	RAND_R_RANDOM_POOL_IS_EMPTY := 16r8E.
	RAND_R_RANDOM_POOL_OVERFLOW := 16r7D.
	RAND_R_RANDOM_POOL_UNDERFLOW := 16r86.
	RAND_R_REQUEST_TOO_LARGE_FOR_DRBG := 16r75.
	RAND_R_RESEED_ERROR := 16r76.
	RAND_R_SELFTEST_FAILURE := 16r77.
	RAND_R_TOO_LITTLE_NONCE_REQUESTED := 16r87.
	RAND_R_TOO_MUCH_NONCE_REQUESTED := 16r88.
	RAND_R_UNABLE_TO_CREATE_DRBG := 16r8F.
	RAND_R_UNABLE_TO_FETCH_DRBG := 16r90.
	RAND_R_UNABLE_TO_GET_PARENT_RESEED_PROP_COUNTER := 16r8D.
	RAND_R_UNABLE_TO_GET_PARENT_STRENGTH := 16r8A.
	RAND_R_UNABLE_TO_LOCK_PARENT := 16r8C.
	RAND_R_UNSUPPORTED_DRBG_FLAGS := 16r84.
	RAND_R_UNSUPPORTED_DRBG_TYPE := 16r78
]
