Class {
	#name : 'SSLConstantsOcsp',
	#superclass : 'SharedPool',
	#classVars : [
		'OCSP_DEFAULT_NONCE_LENGTH',
		'OCSP_NOCASIGN',
		'OCSP_NOCERTS',
		'OCSP_NOCHAIN',
		'OCSP_NOCHECKS',
		'OCSP_NODELEGATED',
		'OCSP_NOEXPLICIT',
		'OCSP_NOINTERN',
		'OCSP_NOSIGS',
		'OCSP_NOTIME',
		'OCSP_NOVERIFY',
		'OCSP_PARTIAL_CHAIN',
		'OCSP_RESPID_KEY',
		'OCSP_RESPONSE_STATUS_INTERNALERROR',
		'OCSP_RESPONSE_STATUS_MALFORMEDREQUEST',
		'OCSP_RESPONSE_STATUS_SIGREQUIRED',
		'OCSP_RESPONSE_STATUS_SUCCESSFUL',
		'OCSP_RESPONSE_STATUS_TRYLATER',
		'OCSP_RESPONSE_STATUS_UNAUTHORIZED',
		'OCSP_REVOKED_STATUS_AACOMPROMISE',
		'OCSP_REVOKED_STATUS_AFFILIATIONCHANGED',
		'OCSP_REVOKED_STATUS_CACOMPROMISE',
		'OCSP_REVOKED_STATUS_CERTIFICATEHOLD',
		'OCSP_REVOKED_STATUS_CESSATIONOFOPERATION',
		'OCSP_REVOKED_STATUS_KEYCOMPROMISE',
		'OCSP_REVOKED_STATUS_NOSTATUS',
		'OCSP_REVOKED_STATUS_PRIVILEGEWITHDRAWN',
		'OCSP_REVOKED_STATUS_REMOVEFROMCRL',
		'OCSP_REVOKED_STATUS_SUPERSEDED',
		'OCSP_REVOKED_STATUS_UNSPECIFIED',
		'OCSP_TRUSTOTHER',
		'PEM_STRING_OCSP_REQUEST',
		'PEM_STRING_OCSP_RESPONSE',
		'V_OCSP_CERTSTATUS_GOOD',
		'V_OCSP_CERTSTATUS_REVOKED',
		'V_OCSP_CERTSTATUS_UNKNOWN',
		'V_OCSP_RESPID_KEY',
		'V_OCSP_RESPID_NAME'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_DEFAULT_NONCE_LENGTH [

	^ OCSP_DEFAULT_NONCE_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOCASIGN [

	^ OCSP_NOCASIGN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOCERTS [

	^ OCSP_NOCERTS
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOCHAIN [

	^ OCSP_NOCHAIN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOCHECKS [

	^ OCSP_NOCHECKS
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NODELEGATED [

	^ OCSP_NODELEGATED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOEXPLICIT [

	^ OCSP_NOEXPLICIT
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOINTERN [

	^ OCSP_NOINTERN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOSIGS [

	^ OCSP_NOSIGS
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOTIME [

	^ OCSP_NOTIME
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_NOVERIFY [

	^ OCSP_NOVERIFY
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_PARTIAL_CHAIN [

	^ OCSP_PARTIAL_CHAIN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPID_KEY [

	^ OCSP_RESPID_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_INTERNALERROR [

	^ OCSP_RESPONSE_STATUS_INTERNALERROR
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_MALFORMEDREQUEST [

	^ OCSP_RESPONSE_STATUS_MALFORMEDREQUEST
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_SIGREQUIRED [

	^ OCSP_RESPONSE_STATUS_SIGREQUIRED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_SUCCESSFUL [

	^ OCSP_RESPONSE_STATUS_SUCCESSFUL
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_TRYLATER [

	^ OCSP_RESPONSE_STATUS_TRYLATER
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_RESPONSE_STATUS_UNAUTHORIZED [

	^ OCSP_RESPONSE_STATUS_UNAUTHORIZED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_AACOMPROMISE [

	^ OCSP_REVOKED_STATUS_AACOMPROMISE
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_AFFILIATIONCHANGED [

	^ OCSP_REVOKED_STATUS_AFFILIATIONCHANGED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_CACOMPROMISE [

	^ OCSP_REVOKED_STATUS_CACOMPROMISE
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_CERTIFICATEHOLD [

	^ OCSP_REVOKED_STATUS_CERTIFICATEHOLD
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_CESSATIONOFOPERATION [

	^ OCSP_REVOKED_STATUS_CESSATIONOFOPERATION
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_KEYCOMPROMISE [

	^ OCSP_REVOKED_STATUS_KEYCOMPROMISE
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_NOSTATUS [

	^ OCSP_REVOKED_STATUS_NOSTATUS
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_PRIVILEGEWITHDRAWN [

	^ OCSP_REVOKED_STATUS_PRIVILEGEWITHDRAWN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_REMOVEFROMCRL [

	^ OCSP_REVOKED_STATUS_REMOVEFROMCRL
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_SUPERSEDED [

	^ OCSP_REVOKED_STATUS_SUPERSEDED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_REVOKED_STATUS_UNSPECIFIED [

	^ OCSP_REVOKED_STATUS_UNSPECIFIED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> OCSP_TRUSTOTHER [

	^ OCSP_TRUSTOTHER
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> PEM_STRING_OCSP_REQUEST [

	^ PEM_STRING_OCSP_REQUEST
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> PEM_STRING_OCSP_RESPONSE [

	^ PEM_STRING_OCSP_RESPONSE
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> V_OCSP_CERTSTATUS_GOOD [

	^ V_OCSP_CERTSTATUS_GOOD
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> V_OCSP_CERTSTATUS_REVOKED [

	^ V_OCSP_CERTSTATUS_REVOKED
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> V_OCSP_CERTSTATUS_UNKNOWN [

	^ V_OCSP_CERTSTATUS_UNKNOWN
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> V_OCSP_RESPID_KEY [

	^ V_OCSP_RESPID_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsOcsp class >> V_OCSP_RESPID_NAME [

	^ V_OCSP_RESPID_NAME
]

{ #category : 'class initialization' }
SSLConstantsOcsp class >> initialize [

	OCSP_REVOKED_STATUS_NOSTATUS := -1.
	OCSP_REVOKED_STATUS_UNSPECIFIED := 0.
	OCSP_REVOKED_STATUS_KEYCOMPROMISE := 1.
	OCSP_REVOKED_STATUS_CACOMPROMISE := 2.
	OCSP_REVOKED_STATUS_AFFILIATIONCHANGED := 3.
	OCSP_REVOKED_STATUS_SUPERSEDED := 4.
	OCSP_REVOKED_STATUS_CESSATIONOFOPERATION := 5.
	OCSP_REVOKED_STATUS_CERTIFICATEHOLD := 6.
	OCSP_REVOKED_STATUS_REMOVEFROMCRL := 8.
	OCSP_REVOKED_STATUS_PRIVILEGEWITHDRAWN := 9.
	OCSP_REVOKED_STATUS_AACOMPROMISE := 10.
	OCSP_DEFAULT_NONCE_LENGTH := 16r10.
	OCSP_NOCERTS := 16r1.
	OCSP_NOINTERN := 16r2.
	OCSP_NOSIGS := 16r4.
	OCSP_NOCHAIN := 16r8.
	OCSP_NOVERIFY := 16r10.
	OCSP_NOEXPLICIT := 16r20.
	OCSP_NOCASIGN := 16r40.
	OCSP_NODELEGATED := 16r80.
	OCSP_NOCHECKS := 16r100.
	OCSP_TRUSTOTHER := 16r200.
	OCSP_RESPID_KEY := 16r400.
	OCSP_NOTIME := 16r800.
	OCSP_PARTIAL_CHAIN := 16r1000.
	OCSP_RESPONSE_STATUS_SUCCESSFUL := 0.
	OCSP_RESPONSE_STATUS_MALFORMEDREQUEST := 1.
	OCSP_RESPONSE_STATUS_INTERNALERROR := 2.
	OCSP_RESPONSE_STATUS_TRYLATER := 3.
	OCSP_RESPONSE_STATUS_SIGREQUIRED := 5.
	OCSP_RESPONSE_STATUS_UNAUTHORIZED := 6.
	V_OCSP_RESPID_NAME := 0.
	V_OCSP_RESPID_KEY := 1.
	V_OCSP_CERTSTATUS_GOOD := 0.
	V_OCSP_CERTSTATUS_REVOKED := 1.
	V_OCSP_CERTSTATUS_UNKNOWN := 2.
	PEM_STRING_OCSP_REQUEST := 'OCSP REQUEST'.
	PEM_STRING_OCSP_RESPONSE := 'OCSP RESPONSE'
]
