Class {
	#name : 'SSLConstantsPemerr',
	#superclass : 'SharedPool',
	#classVars : [
		'PEM_R_BAD_BASE64_DECODE',
		'PEM_R_BAD_DECRYPT',
		'PEM_R_BAD_END_LINE',
		'PEM_R_BAD_IV_CHARS',
		'PEM_R_BAD_MAGIC_NUMBER',
		'PEM_R_BAD_PASSWORD_READ',
		'PEM_R_BAD_VERSION_NUMBER',
		'PEM_R_BIO_WRITE_FAILURE',
		'PEM_R_CIPHER_IS_NULL',
		'PEM_R_ERROR_CONVERTING_PRIVATE_KEY',
		'PEM_R_EXPECTING_DSS_KEY_BLOB',
		'PEM_R_EXPECTING_PRIVATE_KEY_BLOB',
		'PEM_R_EXPECTING_PUBLIC_KEY_BLOB',
		'PEM_R_EXPECTING_RSA_KEY_BLOB',
		'PEM_R_HEADER_TOO_LONG',
		'PEM_R_INCONSISTENT_HEADER',
		'PEM_R_KEYBLOB_HEADER_PARSE_ERROR',
		'PEM_R_KEYBLOB_TOO_SHORT',
		'PEM_R_MISSING_DEK_IV',
		'PEM_R_NOT_DEK_INFO',
		'PEM_R_NOT_ENCRYPTED',
		'PEM_R_NOT_PROC_TYPE',
		'PEM_R_NO_START_LINE',
		'PEM_R_PROBLEMS_GETTING_PASSWORD',
		'PEM_R_PVK_DATA_TOO_SHORT',
		'PEM_R_PVK_TOO_SHORT',
		'PEM_R_READ_KEY',
		'PEM_R_SHORT_HEADER',
		'PEM_R_UNEXPECTED_DEK_IV',
		'PEM_R_UNSUPPORTED_CIPHER',
		'PEM_R_UNSUPPORTED_ENCRYPTION',
		'PEM_R_UNSUPPORTED_KEY_COMPONENTS',
		'PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE',
		'PEM_R_UNSUPPORTED_PVK_KEY_TYPE'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_BASE64_DECODE [

	^ PEM_R_BAD_BASE64_DECODE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_DECRYPT [

	^ PEM_R_BAD_DECRYPT
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_END_LINE [

	^ PEM_R_BAD_END_LINE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_IV_CHARS [

	^ PEM_R_BAD_IV_CHARS
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_MAGIC_NUMBER [

	^ PEM_R_BAD_MAGIC_NUMBER
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_PASSWORD_READ [

	^ PEM_R_BAD_PASSWORD_READ
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BAD_VERSION_NUMBER [

	^ PEM_R_BAD_VERSION_NUMBER
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_BIO_WRITE_FAILURE [

	^ PEM_R_BIO_WRITE_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_CIPHER_IS_NULL [

	^ PEM_R_CIPHER_IS_NULL
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_ERROR_CONVERTING_PRIVATE_KEY [

	^ PEM_R_ERROR_CONVERTING_PRIVATE_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_EXPECTING_DSS_KEY_BLOB [

	^ PEM_R_EXPECTING_DSS_KEY_BLOB
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_EXPECTING_PRIVATE_KEY_BLOB [

	^ PEM_R_EXPECTING_PRIVATE_KEY_BLOB
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_EXPECTING_PUBLIC_KEY_BLOB [

	^ PEM_R_EXPECTING_PUBLIC_KEY_BLOB
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_EXPECTING_RSA_KEY_BLOB [

	^ PEM_R_EXPECTING_RSA_KEY_BLOB
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_HEADER_TOO_LONG [

	^ PEM_R_HEADER_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_INCONSISTENT_HEADER [

	^ PEM_R_INCONSISTENT_HEADER
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_KEYBLOB_HEADER_PARSE_ERROR [

	^ PEM_R_KEYBLOB_HEADER_PARSE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_KEYBLOB_TOO_SHORT [

	^ PEM_R_KEYBLOB_TOO_SHORT
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_MISSING_DEK_IV [

	^ PEM_R_MISSING_DEK_IV
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_NOT_DEK_INFO [

	^ PEM_R_NOT_DEK_INFO
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_NOT_ENCRYPTED [

	^ PEM_R_NOT_ENCRYPTED
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_NOT_PROC_TYPE [

	^ PEM_R_NOT_PROC_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_NO_START_LINE [

	^ PEM_R_NO_START_LINE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_PROBLEMS_GETTING_PASSWORD [

	^ PEM_R_PROBLEMS_GETTING_PASSWORD
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_PVK_DATA_TOO_SHORT [

	^ PEM_R_PVK_DATA_TOO_SHORT
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_PVK_TOO_SHORT [

	^ PEM_R_PVK_TOO_SHORT
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_READ_KEY [

	^ PEM_R_READ_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_SHORT_HEADER [

	^ PEM_R_SHORT_HEADER
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNEXPECTED_DEK_IV [

	^ PEM_R_UNEXPECTED_DEK_IV
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNSUPPORTED_CIPHER [

	^ PEM_R_UNSUPPORTED_CIPHER
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNSUPPORTED_ENCRYPTION [

	^ PEM_R_UNSUPPORTED_ENCRYPTION
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNSUPPORTED_KEY_COMPONENTS [

	^ PEM_R_UNSUPPORTED_KEY_COMPONENTS
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE [

	^ PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsPemerr class >> PEM_R_UNSUPPORTED_PVK_KEY_TYPE [

	^ PEM_R_UNSUPPORTED_PVK_KEY_TYPE
]

{ #category : 'class initialization' }
SSLConstantsPemerr class >> initialize [

	PEM_R_BAD_BASE64_DECODE := 16r64.
	PEM_R_BAD_DECRYPT := 16r65.
	PEM_R_BAD_END_LINE := 16r66.
	PEM_R_BAD_IV_CHARS := 16r67.
	PEM_R_BAD_MAGIC_NUMBER := 16r74.
	PEM_R_BAD_PASSWORD_READ := 16r68.
	PEM_R_BAD_VERSION_NUMBER := 16r75.
	PEM_R_BIO_WRITE_FAILURE := 16r76.
	PEM_R_CIPHER_IS_NULL := 16r7F.
	PEM_R_ERROR_CONVERTING_PRIVATE_KEY := 16r73.
	PEM_R_EXPECTING_DSS_KEY_BLOB := 16r83.
	PEM_R_EXPECTING_PRIVATE_KEY_BLOB := 16r77.
	PEM_R_EXPECTING_PUBLIC_KEY_BLOB := 16r78.
	PEM_R_EXPECTING_RSA_KEY_BLOB := 16r84.
	PEM_R_HEADER_TOO_LONG := 16r80.
	PEM_R_INCONSISTENT_HEADER := 16r79.
	PEM_R_KEYBLOB_HEADER_PARSE_ERROR := 16r7A.
	PEM_R_KEYBLOB_TOO_SHORT := 16r7B.
	PEM_R_MISSING_DEK_IV := 16r81.
	PEM_R_NOT_DEK_INFO := 16r69.
	PEM_R_NOT_ENCRYPTED := 16r6A.
	PEM_R_NOT_PROC_TYPE := 16r6B.
	PEM_R_NO_START_LINE := 16r6C.
	PEM_R_PROBLEMS_GETTING_PASSWORD := 16r6D.
	PEM_R_PVK_DATA_TOO_SHORT := 16r7C.
	PEM_R_PVK_TOO_SHORT := 16r7D.
	PEM_R_READ_KEY := 16r6F.
	PEM_R_SHORT_HEADER := 16r70.
	PEM_R_UNEXPECTED_DEK_IV := 16r82.
	PEM_R_UNSUPPORTED_CIPHER := 16r71.
	PEM_R_UNSUPPORTED_ENCRYPTION := 16r72.
	PEM_R_UNSUPPORTED_KEY_COMPONENTS := 16r7E.
	PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE := 16r6E.
	PEM_R_UNSUPPORTED_PVK_KEY_TYPE := 16r85
]
