Class {
	#name : 'SSLConstantsPem',
	#superclass : 'SharedPool',
	#classVars : [
		'PEM_BUFSIZE',
		'PEM_FLAG_EAY_COMPATIBLE',
		'PEM_FLAG_ONLY_B64',
		'PEM_FLAG_SECURE',
		'PEM_STRING_ACERT',
		'PEM_STRING_CMS',
		'PEM_STRING_DHPARAMS',
		'PEM_STRING_DHXPARAMS',
		'PEM_STRING_DSA',
		'PEM_STRING_DSAPARAMS',
		'PEM_STRING_DSA_PUBLIC',
		'PEM_STRING_ECDSA_PUBLIC',
		'PEM_STRING_ECPARAMETERS',
		'PEM_STRING_ECPRIVATEKEY',
		'PEM_STRING_EVP_PKEY',
		'PEM_STRING_PARAMETERS',
		'PEM_STRING_PKCS7',
		'PEM_STRING_PKCS7_SIGNED',
		'PEM_STRING_PKCS8',
		'PEM_STRING_PKCS8INF',
		'PEM_STRING_PUBLIC',
		'PEM_STRING_RSA',
		'PEM_STRING_RSA_PUBLIC',
		'PEM_STRING_SM2PARAMETERS',
		'PEM_STRING_SM2PRIVATEKEY',
		'PEM_STRING_SSL_SESSION',
		'PEM_STRING_X509',
		'PEM_STRING_X509_CRL',
		'PEM_STRING_X509_OLD',
		'PEM_STRING_X509_REQ',
		'PEM_STRING_X509_REQ_OLD',
		'PEM_STRING_X509_TRUSTED',
		'PEM_TYPE_CLEAR',
		'PEM_TYPE_ENCRYPTED',
		'PEM_TYPE_MIC_CLEAR',
		'PEM_TYPE_MIC_ONLY'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_BUFSIZE [

	^ PEM_BUFSIZE
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_FLAG_EAY_COMPATIBLE [

	^ PEM_FLAG_EAY_COMPATIBLE
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_FLAG_ONLY_B64 [

	^ PEM_FLAG_ONLY_B64
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_FLAG_SECURE [

	^ PEM_FLAG_SECURE
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_ACERT [

	^ PEM_STRING_ACERT
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_CMS [

	^ PEM_STRING_CMS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_DHPARAMS [

	^ PEM_STRING_DHPARAMS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_DHXPARAMS [

	^ PEM_STRING_DHXPARAMS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_DSA [

	^ PEM_STRING_DSA
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_DSAPARAMS [

	^ PEM_STRING_DSAPARAMS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_DSA_PUBLIC [

	^ PEM_STRING_DSA_PUBLIC
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_ECDSA_PUBLIC [

	^ PEM_STRING_ECDSA_PUBLIC
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_ECPARAMETERS [

	^ PEM_STRING_ECPARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_ECPRIVATEKEY [

	^ PEM_STRING_ECPRIVATEKEY
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_EVP_PKEY [

	^ PEM_STRING_EVP_PKEY
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PARAMETERS [

	^ PEM_STRING_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PKCS7 [

	^ PEM_STRING_PKCS7
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PKCS7_SIGNED [

	^ PEM_STRING_PKCS7_SIGNED
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PKCS8 [

	^ PEM_STRING_PKCS8
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PKCS8INF [

	^ PEM_STRING_PKCS8INF
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_PUBLIC [

	^ PEM_STRING_PUBLIC
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_RSA [

	^ PEM_STRING_RSA
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_RSA_PUBLIC [

	^ PEM_STRING_RSA_PUBLIC
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_SM2PARAMETERS [

	^ PEM_STRING_SM2PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_SM2PRIVATEKEY [

	^ PEM_STRING_SM2PRIVATEKEY
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_SSL_SESSION [

	^ PEM_STRING_SSL_SESSION
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509 [

	^ PEM_STRING_X509
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509_CRL [

	^ PEM_STRING_X509_CRL
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509_OLD [

	^ PEM_STRING_X509_OLD
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509_REQ [

	^ PEM_STRING_X509_REQ
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509_REQ_OLD [

	^ PEM_STRING_X509_REQ_OLD
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_STRING_X509_TRUSTED [

	^ PEM_STRING_X509_TRUSTED
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_TYPE_CLEAR [

	^ PEM_TYPE_CLEAR
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_TYPE_ENCRYPTED [

	^ PEM_TYPE_ENCRYPTED
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_TYPE_MIC_CLEAR [

	^ PEM_TYPE_MIC_CLEAR
]

{ #category : 'accessing - constants' }
SSLConstantsPem class >> PEM_TYPE_MIC_ONLY [

	^ PEM_TYPE_MIC_ONLY
]

{ #category : 'class initialization' }
SSLConstantsPem class >> initialize [

	PEM_BUFSIZE := 16r400.
	PEM_STRING_X509_OLD := 'X509 CERTIFICATE'.
	PEM_STRING_X509 := 'CERTIFICATE'.
	PEM_STRING_X509_TRUSTED := 'TRUSTED CERTIFICATE'.
	PEM_STRING_X509_REQ_OLD := 'NEW CERTIFICATE REQUEST'.
	PEM_STRING_X509_REQ := 'CERTIFICATE REQUEST'.
	PEM_STRING_X509_CRL := 'X509 CRL'.
	PEM_STRING_EVP_PKEY := 'ANY PRIVATE KEY'.
	PEM_STRING_PUBLIC := 'PUBLIC KEY'.
	PEM_STRING_RSA := 'RSA PRIVATE KEY'.
	PEM_STRING_RSA_PUBLIC := 'RSA PUBLIC KEY'.
	PEM_STRING_DSA := 'DSA PRIVATE KEY'.
	PEM_STRING_DSA_PUBLIC := 'DSA PUBLIC KEY'.
	PEM_STRING_PKCS7 := 'PKCS7'.
	PEM_STRING_PKCS7_SIGNED := 'PKCS #7 SIGNED DATA'.
	PEM_STRING_PKCS8 := 'ENCRYPTED PRIVATE KEY'.
	PEM_STRING_PKCS8INF := 'PRIVATE KEY'.
	PEM_STRING_DHPARAMS := 'DH PARAMETERS'.
	PEM_STRING_DHXPARAMS := 'X9.42 DH PARAMETERS'.
	PEM_STRING_SSL_SESSION := 'SSL SESSION PARAMETERS'.
	PEM_STRING_DSAPARAMS := 'DSA PARAMETERS'.
	PEM_STRING_ECDSA_PUBLIC := 'ECDSA PUBLIC KEY'.
	PEM_STRING_ECPARAMETERS := 'EC PARAMETERS'.
	PEM_STRING_ECPRIVATEKEY := 'EC PRIVATE KEY'.
	PEM_STRING_PARAMETERS := 'PARAMETERS'.
	PEM_STRING_CMS := 'CMS'.
	PEM_STRING_SM2PRIVATEKEY := 'SM2 PRIVATE KEY'.
	PEM_STRING_SM2PARAMETERS := 'SM2 PARAMETERS'.
	PEM_STRING_ACERT := 'ATTRIBUTE CERTIFICATE'.
	PEM_TYPE_ENCRYPTED := 10.
	PEM_TYPE_MIC_ONLY := 16r14.
	PEM_TYPE_MIC_CLEAR := 16r1E.
	PEM_TYPE_CLEAR := 16r28.
	PEM_FLAG_SECURE := 16r1.
	PEM_FLAG_EAY_COMPATIBLE := 16r2.
	PEM_FLAG_ONLY_B64 := 16r4
]
