Class {
	#name : 'SSLConstantsBioerr',
	#superclass : 'SharedPool',
	#classVars : [
		'BIO_R_ACCEPT_ERROR',
		'BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET',
		'BIO_R_AMBIGUOUS_HOST_OR_SERVICE',
		'BIO_R_BAD_FOPEN_MODE',
		'BIO_R_BROKEN_PIPE',
		'BIO_R_CONNECT_ERROR',
		'BIO_R_CONNECT_TIMEOUT',
		'BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET',
		'BIO_R_GETSOCKNAME_ERROR',
		'BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS',
		'BIO_R_GETTING_SOCKTYPE',
		'BIO_R_INVALID_ARGUMENT',
		'BIO_R_INVALID_SOCKET',
		'BIO_R_IN_USE',
		'BIO_R_LENGTH_TOO_LONG',
		'BIO_R_LISTEN_V6_ONLY',
		'BIO_R_LOCAL_ADDR_NOT_AVAILABLE',
		'BIO_R_LOOKUP_RETURNED_NOTHING',
		'BIO_R_MALFORMED_HOST_OR_SERVICE',
		'BIO_R_NBIO_CONNECT_ERROR',
		'BIO_R_NON_FATAL',
		'BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED',
		'BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED',
		'BIO_R_NO_PORT_DEFINED',
		'BIO_R_NO_SUCH_FILE',
		'BIO_R_NULL_PARAMETER',
		'BIO_R_PEER_ADDR_NOT_AVAILABLE',
		'BIO_R_PORT_MISMATCH',
		'BIO_R_TFO_DISABLED',
		'BIO_R_TFO_NO_KERNEL_SUPPORT',
		'BIO_R_TRANSFER_ERROR',
		'BIO_R_TRANSFER_TIMEOUT',
		'BIO_R_UNABLE_TO_BIND_SOCKET',
		'BIO_R_UNABLE_TO_CREATE_SOCKET',
		'BIO_R_UNABLE_TO_KEEPALIVE',
		'BIO_R_UNABLE_TO_LISTEN_SOCKET',
		'BIO_R_UNABLE_TO_NODELAY',
		'BIO_R_UNABLE_TO_REUSEADDR',
		'BIO_R_UNABLE_TO_TFO',
		'BIO_R_UNAVAILABLE_IP_FAMILY',
		'BIO_R_UNINITIALIZED',
		'BIO_R_UNKNOWN_INFO_TYPE',
		'BIO_R_UNSUPPORTED_IP_FAMILY',
		'BIO_R_UNSUPPORTED_METHOD',
		'BIO_R_UNSUPPORTED_PROTOCOL_FAMILY',
		'BIO_R_WRITE_TO_READ_ONLY_BIO',
		'BIO_R_WSASTARTUP'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_ACCEPT_ERROR [

	^ BIO_R_ACCEPT_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET [

	^ BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_AMBIGUOUS_HOST_OR_SERVICE [

	^ BIO_R_AMBIGUOUS_HOST_OR_SERVICE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_BAD_FOPEN_MODE [

	^ BIO_R_BAD_FOPEN_MODE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_BROKEN_PIPE [

	^ BIO_R_BROKEN_PIPE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_CONNECT_ERROR [

	^ BIO_R_CONNECT_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_CONNECT_TIMEOUT [

	^ BIO_R_CONNECT_TIMEOUT
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET [

	^ BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_GETSOCKNAME_ERROR [

	^ BIO_R_GETSOCKNAME_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS [

	^ BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_GETTING_SOCKTYPE [

	^ BIO_R_GETTING_SOCKTYPE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_INVALID_ARGUMENT [

	^ BIO_R_INVALID_ARGUMENT
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_INVALID_SOCKET [

	^ BIO_R_INVALID_SOCKET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_IN_USE [

	^ BIO_R_IN_USE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_LENGTH_TOO_LONG [

	^ BIO_R_LENGTH_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_LISTEN_V6_ONLY [

	^ BIO_R_LISTEN_V6_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_LOCAL_ADDR_NOT_AVAILABLE [

	^ BIO_R_LOCAL_ADDR_NOT_AVAILABLE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_LOOKUP_RETURNED_NOTHING [

	^ BIO_R_LOOKUP_RETURNED_NOTHING
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_MALFORMED_HOST_OR_SERVICE [

	^ BIO_R_MALFORMED_HOST_OR_SERVICE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NBIO_CONNECT_ERROR [

	^ BIO_R_NBIO_CONNECT_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NON_FATAL [

	^ BIO_R_NON_FATAL
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED [

	^ BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED [

	^ BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NO_PORT_DEFINED [

	^ BIO_R_NO_PORT_DEFINED
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NO_SUCH_FILE [

	^ BIO_R_NO_SUCH_FILE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_NULL_PARAMETER [

	^ BIO_R_NULL_PARAMETER
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_PEER_ADDR_NOT_AVAILABLE [

	^ BIO_R_PEER_ADDR_NOT_AVAILABLE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_PORT_MISMATCH [

	^ BIO_R_PORT_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_TFO_DISABLED [

	^ BIO_R_TFO_DISABLED
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_TFO_NO_KERNEL_SUPPORT [

	^ BIO_R_TFO_NO_KERNEL_SUPPORT
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_TRANSFER_ERROR [

	^ BIO_R_TRANSFER_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_TRANSFER_TIMEOUT [

	^ BIO_R_TRANSFER_TIMEOUT
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_BIND_SOCKET [

	^ BIO_R_UNABLE_TO_BIND_SOCKET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_CREATE_SOCKET [

	^ BIO_R_UNABLE_TO_CREATE_SOCKET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_KEEPALIVE [

	^ BIO_R_UNABLE_TO_KEEPALIVE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_LISTEN_SOCKET [

	^ BIO_R_UNABLE_TO_LISTEN_SOCKET
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_NODELAY [

	^ BIO_R_UNABLE_TO_NODELAY
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_REUSEADDR [

	^ BIO_R_UNABLE_TO_REUSEADDR
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNABLE_TO_TFO [

	^ BIO_R_UNABLE_TO_TFO
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNAVAILABLE_IP_FAMILY [

	^ BIO_R_UNAVAILABLE_IP_FAMILY
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNINITIALIZED [

	^ BIO_R_UNINITIALIZED
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNKNOWN_INFO_TYPE [

	^ BIO_R_UNKNOWN_INFO_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNSUPPORTED_IP_FAMILY [

	^ BIO_R_UNSUPPORTED_IP_FAMILY
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNSUPPORTED_METHOD [

	^ BIO_R_UNSUPPORTED_METHOD
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_UNSUPPORTED_PROTOCOL_FAMILY [

	^ BIO_R_UNSUPPORTED_PROTOCOL_FAMILY
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_WRITE_TO_READ_ONLY_BIO [

	^ BIO_R_WRITE_TO_READ_ONLY_BIO
]

{ #category : 'accessing - constants' }
SSLConstantsBioerr class >> BIO_R_WSASTARTUP [

	^ BIO_R_WSASTARTUP
]

{ #category : 'class initialization' }
SSLConstantsBioerr class >> initialize [

	BIO_R_ACCEPT_ERROR := 16r64.
	BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET := 16r8D.
	BIO_R_AMBIGUOUS_HOST_OR_SERVICE := 16r81.
	BIO_R_BAD_FOPEN_MODE := 16r65.
	BIO_R_BROKEN_PIPE := 16r7C.
	BIO_R_CONNECT_ERROR := 16r67.
	BIO_R_CONNECT_TIMEOUT := 16r93.
	BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET := 16r6B.
	BIO_R_GETSOCKNAME_ERROR := 16r84.
	BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS := 16r85.
	BIO_R_GETTING_SOCKTYPE := 16r86.
	BIO_R_INVALID_ARGUMENT := 16r7D.
	BIO_R_INVALID_SOCKET := 16r87.
	BIO_R_IN_USE := 16r7B.
	BIO_R_LENGTH_TOO_LONG := 16r66.
	BIO_R_LISTEN_V6_ONLY := 16r88.
	BIO_R_LOCAL_ADDR_NOT_AVAILABLE := 16r6F.
	BIO_R_LOOKUP_RETURNED_NOTHING := 16r8E.
	BIO_R_MALFORMED_HOST_OR_SERVICE := 16r82.
	BIO_R_NBIO_CONNECT_ERROR := 16r6E.
	BIO_R_NON_FATAL := 16r70.
	BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED := 16r8F.
	BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED := 16r90.
	BIO_R_NO_PORT_DEFINED := 16r71.
	BIO_R_NO_SUCH_FILE := 16r80.
	BIO_R_NULL_PARAMETER := 16r73.
	BIO_R_TFO_DISABLED := 16r6A.
	BIO_R_TFO_NO_KERNEL_SUPPORT := 16r6C.
	BIO_R_TRANSFER_ERROR := 16r68.
	BIO_R_TRANSFER_TIMEOUT := 16r69.
	BIO_R_UNABLE_TO_BIND_SOCKET := 16r75.
	BIO_R_UNABLE_TO_CREATE_SOCKET := 16r76.
	BIO_R_UNABLE_TO_KEEPALIVE := 16r89.
	BIO_R_UNABLE_TO_LISTEN_SOCKET := 16r77.
	BIO_R_UNABLE_TO_NODELAY := 16r8A.
	BIO_R_UNABLE_TO_REUSEADDR := 16r8B.
	BIO_R_UNABLE_TO_TFO := 16r6D.
	BIO_R_UNAVAILABLE_IP_FAMILY := 16r91.
	BIO_R_UNINITIALIZED := 16r78.
	BIO_R_UNKNOWN_INFO_TYPE := 16r8C.
	BIO_R_UNSUPPORTED_IP_FAMILY := 16r92.
	BIO_R_UNSUPPORTED_METHOD := 16r79.
	BIO_R_UNSUPPORTED_PROTOCOL_FAMILY := 16r83.
	BIO_R_WRITE_TO_READ_ONLY_BIO := 16r7E.
	BIO_R_WSASTARTUP := 16r7A.
	BIO_R_PORT_MISMATCH := 16r96.
	BIO_R_PEER_ADDR_NOT_AVAILABLE := 16r97
]
