Class {
	#name : 'SSLConstantsAsn1t',
	#superclass : 'SharedPool',
	#classVars : [
		'ASN1_AFLG_BROKEN',
		'ASN1_AFLG_CONST_CB',
		'ASN1_AFLG_ENCODING',
		'ASN1_AFLG_REFCOUNT',
		'ASN1_ITYPE_CHOICE',
		'ASN1_ITYPE_EXTERN',
		'ASN1_ITYPE_MSTRING',
		'ASN1_ITYPE_NDEF_SEQUENCE',
		'ASN1_ITYPE_PRIMITIVE',
		'ASN1_ITYPE_SEQUENCE',
		'ASN1_OP_D2I_POST',
		'ASN1_OP_D2I_PRE',
		'ASN1_OP_DETACHED_POST',
		'ASN1_OP_DETACHED_PRE',
		'ASN1_OP_DUP_POST',
		'ASN1_OP_DUP_PRE',
		'ASN1_OP_FREE_POST',
		'ASN1_OP_FREE_PRE',
		'ASN1_OP_GET0_LIBCTX',
		'ASN1_OP_GET0_PROPQ',
		'ASN1_OP_I2D_POST',
		'ASN1_OP_I2D_PRE',
		'ASN1_OP_NEW_POST',
		'ASN1_OP_NEW_PRE',
		'ASN1_OP_PRINT_POST',
		'ASN1_OP_PRINT_PRE',
		'ASN1_OP_STREAM_POST',
		'ASN1_OP_STREAM_PRE',
		'ASN1_TFLG_ADB_INT',
		'ASN1_TFLG_ADB_MASK',
		'ASN1_TFLG_ADB_OID',
		'ASN1_TFLG_APPLICATION',
		'ASN1_TFLG_CONTEXT',
		'ASN1_TFLG_EMBED',
		'ASN1_TFLG_EXPLICIT',
		'ASN1_TFLG_EXPTAG',
		'ASN1_TFLG_IMPLICIT',
		'ASN1_TFLG_IMPTAG',
		'ASN1_TFLG_NDEF',
		'ASN1_TFLG_OPTIONAL',
		'ASN1_TFLG_PRIVATE',
		'ASN1_TFLG_SEQUENCE_OF',
		'ASN1_TFLG_SET_OF',
		'ASN1_TFLG_SET_ORDER',
		'ASN1_TFLG_SK_MASK',
		'ASN1_TFLG_TAG_CLASS',
		'ASN1_TFLG_TAG_MASK',
		'ASN1_TFLG_UNIVERSAL'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_AFLG_BROKEN [

	^ ASN1_AFLG_BROKEN
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_AFLG_CONST_CB [

	^ ASN1_AFLG_CONST_CB
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_AFLG_ENCODING [

	^ ASN1_AFLG_ENCODING
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_AFLG_REFCOUNT [

	^ ASN1_AFLG_REFCOUNT
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_CHOICE [

	^ ASN1_ITYPE_CHOICE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_EXTERN [

	^ ASN1_ITYPE_EXTERN
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_MSTRING [

	^ ASN1_ITYPE_MSTRING
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_NDEF_SEQUENCE [

	^ ASN1_ITYPE_NDEF_SEQUENCE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_PRIMITIVE [

	^ ASN1_ITYPE_PRIMITIVE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_ITYPE_SEQUENCE [

	^ ASN1_ITYPE_SEQUENCE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_D2I_POST [

	^ ASN1_OP_D2I_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_D2I_PRE [

	^ ASN1_OP_D2I_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_DETACHED_POST [

	^ ASN1_OP_DETACHED_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_DETACHED_PRE [

	^ ASN1_OP_DETACHED_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_DUP_POST [

	^ ASN1_OP_DUP_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_DUP_PRE [

	^ ASN1_OP_DUP_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_FREE_POST [

	^ ASN1_OP_FREE_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_FREE_PRE [

	^ ASN1_OP_FREE_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_GET0_LIBCTX [

	^ ASN1_OP_GET0_LIBCTX
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_GET0_PROPQ [

	^ ASN1_OP_GET0_PROPQ
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_I2D_POST [

	^ ASN1_OP_I2D_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_I2D_PRE [

	^ ASN1_OP_I2D_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_NEW_POST [

	^ ASN1_OP_NEW_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_NEW_PRE [

	^ ASN1_OP_NEW_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_PRINT_POST [

	^ ASN1_OP_PRINT_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_PRINT_PRE [

	^ ASN1_OP_PRINT_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_STREAM_POST [

	^ ASN1_OP_STREAM_POST
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_OP_STREAM_PRE [

	^ ASN1_OP_STREAM_PRE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_ADB_INT [

	^ ASN1_TFLG_ADB_INT
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_ADB_MASK [

	^ ASN1_TFLG_ADB_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_ADB_OID [

	^ ASN1_TFLG_ADB_OID
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_APPLICATION [

	^ ASN1_TFLG_APPLICATION
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_CONTEXT [

	^ ASN1_TFLG_CONTEXT
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_EMBED [

	^ ASN1_TFLG_EMBED
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_EXPLICIT [

	^ ASN1_TFLG_EXPLICIT
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_EXPTAG [

	^ ASN1_TFLG_EXPTAG
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_IMPLICIT [

	^ ASN1_TFLG_IMPLICIT
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_IMPTAG [

	^ ASN1_TFLG_IMPTAG
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_NDEF [

	^ ASN1_TFLG_NDEF
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_OPTIONAL [

	^ ASN1_TFLG_OPTIONAL
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_PRIVATE [

	^ ASN1_TFLG_PRIVATE
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_SEQUENCE_OF [

	^ ASN1_TFLG_SEQUENCE_OF
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_SET_OF [

	^ ASN1_TFLG_SET_OF
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_SET_ORDER [

	^ ASN1_TFLG_SET_ORDER
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_SK_MASK [

	^ ASN1_TFLG_SK_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_TAG_CLASS [

	^ ASN1_TFLG_TAG_CLASS
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_TAG_MASK [

	^ ASN1_TFLG_TAG_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsAsn1t class >> ASN1_TFLG_UNIVERSAL [

	^ ASN1_TFLG_UNIVERSAL
]

{ #category : 'class initialization' }
SSLConstantsAsn1t class >> initialize [

	ASN1_ITYPE_PRIMITIVE := 16r0.
	ASN1_ITYPE_SEQUENCE := 16r1.
	ASN1_ITYPE_CHOICE := 16r2.
	ASN1_ITYPE_EXTERN := 16r4.
	ASN1_ITYPE_MSTRING := 16r5.
	ASN1_ITYPE_NDEF_SEQUENCE := 16r6.
	ASN1_TFLG_OPTIONAL := 1	 "(0x1)".
	ASN1_TFLG_SET_OF := 2	 "(0x1 << 1)".
	ASN1_TFLG_SEQUENCE_OF := 4	 "(0x2 << 1)".
	ASN1_TFLG_SET_ORDER := 6	 "(0x3 << 1)".
	ASN1_TFLG_SK_MASK := 6	 "(0x3 << 1)".
	ASN1_TFLG_IMPTAG := 8	 "(0x1 << 3)".
	ASN1_TFLG_EXPTAG := 16r10	 "(0x2 << 3)".
	ASN1_TFLG_TAG_MASK := 16r18	 "(0x3 << 3)".
	ASN1_TFLG_IMPLICIT := 16r88	 "(ASN1_TFLG_IMPTAG|ASN1_TFLG_CONTEXT)".
	ASN1_TFLG_EXPLICIT := 16r90	 "(ASN1_TFLG_EXPTAG|ASN1_TFLG_CONTEXT)".
	ASN1_TFLG_UNIVERSAL := 0	 "(0x0<<6)".
	ASN1_TFLG_APPLICATION := 16r40	 "(0x1<<6)".
	ASN1_TFLG_CONTEXT := 16r80	 "(0x2<<6)".
	ASN1_TFLG_PRIVATE := 16rC0	 "(0x3<<6)".
	ASN1_TFLG_TAG_CLASS := 16rC0	 "(0x3<<6)".
	ASN1_TFLG_ADB_MASK := 16r300	 "(0x3<<8)".
	ASN1_TFLG_ADB_OID := 16r100	 "(0x1<<8)".
	ASN1_TFLG_ADB_INT := 16r200	 "(0x1<<9)".
	ASN1_TFLG_NDEF := 16r800	 "(0x1<<11)".
	ASN1_TFLG_EMBED := 16r1000	 "(0x1 << 12)".
	ASN1_AFLG_REFCOUNT := 1.
	ASN1_AFLG_ENCODING := 2.
	ASN1_AFLG_BROKEN := 4.
	ASN1_AFLG_CONST_CB := 8.
	ASN1_OP_NEW_PRE := 0.
	ASN1_OP_NEW_POST := 1.
	ASN1_OP_FREE_PRE := 2.
	ASN1_OP_FREE_POST := 3.
	ASN1_OP_D2I_PRE := 4.
	ASN1_OP_D2I_POST := 5.
	ASN1_OP_I2D_PRE := 6.
	ASN1_OP_I2D_POST := 7.
	ASN1_OP_PRINT_PRE := 8.
	ASN1_OP_PRINT_POST := 9.
	ASN1_OP_STREAM_PRE := 10.
	ASN1_OP_STREAM_POST := 11.
	ASN1_OP_DETACHED_PRE := 12.
	ASN1_OP_DETACHED_POST := 13.
	ASN1_OP_DUP_PRE := 14.
	ASN1_OP_DUP_POST := 15.
	ASN1_OP_GET0_LIBCTX := 16r10.
	ASN1_OP_GET0_PROPQ := 16r11
]
