Class {
	#name : 'SSLConstantsRsa',
	#superclass : 'SharedPool',
	#classVars : [
		'EVP_PKEY_CTRL_GET_RSA_MGF1_MD',
		'EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL',
		'EVP_PKEY_CTRL_GET_RSA_OAEP_MD',
		'EVP_PKEY_CTRL_GET_RSA_PADDING',
		'EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN',
		'EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION',
		'EVP_PKEY_CTRL_RSA_KEYGEN_BITS',
		'EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES',
		'EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP',
		'EVP_PKEY_CTRL_RSA_MGF1_MD',
		'EVP_PKEY_CTRL_RSA_OAEP_LABEL',
		'EVP_PKEY_CTRL_RSA_OAEP_MD',
		'EVP_PKEY_CTRL_RSA_PADDING',
		'EVP_PKEY_CTRL_RSA_PSS_SALTLEN',
		'OPENSSL_RSA_FIPS_MIN_MODULUS_BITS',
		'OPENSSL_RSA_MAX_MODULUS_BITS',
		'OPENSSL_RSA_MAX_PUBEXP_BITS',
		'OPENSSL_RSA_SMALL_MODULUS_BITS',
		'RSA_3',
		'RSA_ASN1_VERSION_DEFAULT',
		'RSA_ASN1_VERSION_MULTI',
		'RSA_DEFAULT_PRIME_NUM',
		'RSA_F4',
		'RSA_FLAG_BLINDING',
		'RSA_FLAG_CACHE_PRIVATE',
		'RSA_FLAG_CACHE_PUBLIC',
		'RSA_FLAG_CHECKED',
		'RSA_FLAG_EXT_PKEY',
		'RSA_FLAG_FIPS_METHOD',
		'RSA_FLAG_NON_FIPS_ALLOW',
		'RSA_FLAG_NO_BLINDING',
		'RSA_FLAG_NO_CONSTTIME',
		'RSA_FLAG_NO_EXP_CONSTTIME',
		'RSA_FLAG_THREAD_SAFE',
		'RSA_FLAG_TYPE_MASK',
		'RSA_FLAG_TYPE_RSA',
		'RSA_FLAG_TYPE_RSAESOAEP',
		'RSA_FLAG_TYPE_RSASSAPSS',
		'RSA_METHOD_FLAG_NO_CHECK',
		'RSA_NO_PADDING',
		'RSA_PKCS1_NO_IMPLICIT_REJECT_PADDING',
		'RSA_PKCS1_OAEP_PADDING',
		'RSA_PKCS1_PADDING',
		'RSA_PKCS1_PADDING_SIZE',
		'RSA_PKCS1_PSS_PADDING',
		'RSA_PKCS1_WITH_TLS_PADDING',
		'RSA_PSS_SALTLEN_AUTO',
		'RSA_PSS_SALTLEN_AUTO_DIGEST_MAX',
		'RSA_PSS_SALTLEN_DIGEST',
		'RSA_PSS_SALTLEN_MAX',
		'RSA_PSS_SALTLEN_MAX_SIGN',
		'RSA_X931_PADDING'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_GET_RSA_MGF1_MD [

	^ EVP_PKEY_CTRL_GET_RSA_MGF1_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL [

	^ EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_GET_RSA_OAEP_MD [

	^ EVP_PKEY_CTRL_GET_RSA_OAEP_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_GET_RSA_PADDING [

	^ EVP_PKEY_CTRL_GET_RSA_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN [

	^ EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION [

	^ EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_KEYGEN_BITS [

	^ EVP_PKEY_CTRL_RSA_KEYGEN_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES [

	^ EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP [

	^ EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_MGF1_MD [

	^ EVP_PKEY_CTRL_RSA_MGF1_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_OAEP_LABEL [

	^ EVP_PKEY_CTRL_RSA_OAEP_LABEL
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_OAEP_MD [

	^ EVP_PKEY_CTRL_RSA_OAEP_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_PADDING [

	^ EVP_PKEY_CTRL_RSA_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> EVP_PKEY_CTRL_RSA_PSS_SALTLEN [

	^ EVP_PKEY_CTRL_RSA_PSS_SALTLEN
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> OPENSSL_RSA_FIPS_MIN_MODULUS_BITS [

	^ OPENSSL_RSA_FIPS_MIN_MODULUS_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> OPENSSL_RSA_MAX_MODULUS_BITS [

	^ OPENSSL_RSA_MAX_MODULUS_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> OPENSSL_RSA_MAX_PUBEXP_BITS [

	^ OPENSSL_RSA_MAX_PUBEXP_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> OPENSSL_RSA_SMALL_MODULUS_BITS [

	^ OPENSSL_RSA_SMALL_MODULUS_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_3 [

	^ RSA_3
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_ASN1_VERSION_DEFAULT [

	^ RSA_ASN1_VERSION_DEFAULT
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_ASN1_VERSION_MULTI [

	^ RSA_ASN1_VERSION_MULTI
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_DEFAULT_PRIME_NUM [

	^ RSA_DEFAULT_PRIME_NUM
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_F4 [

	^ RSA_F4
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_BLINDING [

	^ RSA_FLAG_BLINDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_CACHE_PRIVATE [

	^ RSA_FLAG_CACHE_PRIVATE
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_CACHE_PUBLIC [

	^ RSA_FLAG_CACHE_PUBLIC
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_CHECKED [

	^ RSA_FLAG_CHECKED
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_EXT_PKEY [

	^ RSA_FLAG_EXT_PKEY
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_FIPS_METHOD [

	^ RSA_FLAG_FIPS_METHOD
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_NON_FIPS_ALLOW [

	^ RSA_FLAG_NON_FIPS_ALLOW
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_NO_BLINDING [

	^ RSA_FLAG_NO_BLINDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_NO_CONSTTIME [

	^ RSA_FLAG_NO_CONSTTIME
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_NO_EXP_CONSTTIME [

	^ RSA_FLAG_NO_EXP_CONSTTIME
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_THREAD_SAFE [

	^ RSA_FLAG_THREAD_SAFE
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_TYPE_MASK [

	^ RSA_FLAG_TYPE_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_TYPE_RSA [

	^ RSA_FLAG_TYPE_RSA
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_TYPE_RSAESOAEP [

	^ RSA_FLAG_TYPE_RSAESOAEP
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_FLAG_TYPE_RSASSAPSS [

	^ RSA_FLAG_TYPE_RSASSAPSS
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_METHOD_FLAG_NO_CHECK [

	^ RSA_METHOD_FLAG_NO_CHECK
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_NO_PADDING [

	^ RSA_NO_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_NO_IMPLICIT_REJECT_PADDING [

	^ RSA_PKCS1_NO_IMPLICIT_REJECT_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_OAEP_PADDING [

	^ RSA_PKCS1_OAEP_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_PADDING [

	^ RSA_PKCS1_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_PADDING_SIZE [

	^ RSA_PKCS1_PADDING_SIZE
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_PSS_PADDING [

	^ RSA_PKCS1_PSS_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PKCS1_WITH_TLS_PADDING [

	^ RSA_PKCS1_WITH_TLS_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PSS_SALTLEN_AUTO [

	^ RSA_PSS_SALTLEN_AUTO
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PSS_SALTLEN_AUTO_DIGEST_MAX [

	^ RSA_PSS_SALTLEN_AUTO_DIGEST_MAX
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PSS_SALTLEN_DIGEST [

	^ RSA_PSS_SALTLEN_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PSS_SALTLEN_MAX [

	^ RSA_PSS_SALTLEN_MAX
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_PSS_SALTLEN_MAX_SIGN [

	^ RSA_PSS_SALTLEN_MAX_SIGN
]

{ #category : 'accessing - constants' }
SSLConstantsRsa class >> RSA_X931_PADDING [

	^ RSA_X931_PADDING
]

{ #category : 'class initialization' }
SSLConstantsRsa class >> initialize [

	OPENSSL_RSA_MAX_MODULUS_BITS := 16r4000.
	RSA_3 := 16r3.
	RSA_F4 := 16r10001.
	OPENSSL_RSA_FIPS_MIN_MODULUS_BITS := 16r800.
	OPENSSL_RSA_SMALL_MODULUS_BITS := 16rC00.
	OPENSSL_RSA_MAX_PUBEXP_BITS := 16r40.
	RSA_ASN1_VERSION_DEFAULT := 0.
	RSA_ASN1_VERSION_MULTI := 1.
	RSA_DEFAULT_PRIME_NUM := 2.
	RSA_METHOD_FLAG_NO_CHECK := 16r0001.
	RSA_FLAG_CACHE_PUBLIC := 16r0002.
	RSA_FLAG_CACHE_PRIVATE := 16r0004.
	RSA_FLAG_BLINDING := 16r0008.
	RSA_FLAG_THREAD_SAFE := 16r0010.
	RSA_FLAG_EXT_PKEY := 16r0020.
	RSA_FLAG_NO_BLINDING := 16r0080.
	RSA_FLAG_NO_CONSTTIME := 16r0000.
	RSA_FLAG_NO_EXP_CONSTTIME := 0	 "RSA_FLAG_NO_CONSTTIME".
	RSA_FLAG_TYPE_MASK := 16rF000.
	RSA_FLAG_TYPE_RSA := 16r0000.
	RSA_FLAG_TYPE_RSASSAPSS := 16r1000.
	RSA_FLAG_TYPE_RSAESOAEP := 16r2000.
	RSA_PSS_SALTLEN_DIGEST := -1.
	RSA_PSS_SALTLEN_AUTO := -2.
	RSA_PSS_SALTLEN_MAX := -3.
	RSA_PSS_SALTLEN_AUTO_DIGEST_MAX := -4.
	RSA_PSS_SALTLEN_MAX_SIGN := -2.
	EVP_PKEY_CTRL_RSA_PADDING := 16r1001	 "(EVP_PKEY_ALG_CTRL + 1)".
	EVP_PKEY_CTRL_RSA_PSS_SALTLEN := 16r1002	 "(EVP_PKEY_ALG_CTRL + 2)".
	EVP_PKEY_CTRL_RSA_KEYGEN_BITS := 16r1003	 "(EVP_PKEY_ALG_CTRL + 3)".
	EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP := 16r1004	 "(EVP_PKEY_ALG_CTRL + 4)".
	EVP_PKEY_CTRL_RSA_MGF1_MD := 16r1005	 "(EVP_PKEY_ALG_CTRL + 5)".
	EVP_PKEY_CTRL_GET_RSA_PADDING := 16r1006	 "(EVP_PKEY_ALG_CTRL + 6)".
	EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN := 16r1007	 "(EVP_PKEY_ALG_CTRL + 7)".
	EVP_PKEY_CTRL_GET_RSA_MGF1_MD := 16r1008	 "(EVP_PKEY_ALG_CTRL + 8)".
	EVP_PKEY_CTRL_RSA_OAEP_MD := 16r1009	 "(EVP_PKEY_ALG_CTRL + 9)".
	EVP_PKEY_CTRL_RSA_OAEP_LABEL := 16r100A	 "(EVP_PKEY_ALG_CTRL + 10)".
	EVP_PKEY_CTRL_GET_RSA_OAEP_MD := 16r100B	 "(EVP_PKEY_ALG_CTRL + 11)".
	EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL := 16r100C	 "(EVP_PKEY_ALG_CTRL + 12)".
	EVP_PKEY_CTRL_RSA_KEYGEN_PRIMES := 16r100D	 "(EVP_PKEY_ALG_CTRL + 13)".
	EVP_PKEY_CTRL_RSA_IMPLICIT_REJECTION := 16r100E	 "(EVP_PKEY_ALG_CTRL + 14)".
	RSA_PKCS1_PADDING := 1.
	RSA_NO_PADDING := 3.
	RSA_PKCS1_OAEP_PADDING := 4.
	RSA_X931_PADDING := 5.
	RSA_PKCS1_PSS_PADDING := 6.
	RSA_PKCS1_WITH_TLS_PADDING := 7.
	RSA_PKCS1_NO_IMPLICIT_REJECT_PADDING := 8.
	RSA_PKCS1_PADDING_SIZE := 11.
	RSA_FLAG_FIPS_METHOD := 16r0400.
	RSA_FLAG_NON_FIPS_ALLOW := 16r0400.
	RSA_FLAG_CHECKED := 16r0800
]
