Class {
	#name : 'SSLConstantsEcerr',
	#superclass : 'SharedPool',
	#classVars : [
		'EC_R_ASN1_ERROR',
		'EC_R_BAD_SIGNATURE',
		'EC_R_BIGNUM_OUT_OF_RANGE',
		'EC_R_BUFFER_TOO_SMALL',
		'EC_R_CANNOT_INVERT',
		'EC_R_COORDINATES_OUT_OF_RANGE',
		'EC_R_CURVE_DOES_NOT_SUPPORT_ECDH',
		'EC_R_CURVE_DOES_NOT_SUPPORT_ECDSA',
		'EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING',
		'EC_R_DECODE_ERROR',
		'EC_R_DISCRIMINANT_IS_ZERO',
		'EC_R_EC_GROUP_NEW_BY_NAME_FAILURE',
		'EC_R_EXPLICIT_PARAMS_NOT_SUPPORTED',
		'EC_R_FAILED_MAKING_PUBLIC_KEY',
		'EC_R_FIELD_TOO_LARGE',
		'EC_R_GF2M_NOT_SUPPORTED',
		'EC_R_GROUP2PKPARAMETERS_FAILURE',
		'EC_R_I2D_ECPKPARAMETERS_FAILURE',
		'EC_R_INCOMPATIBLE_OBJECTS',
		'EC_R_INVALID_A',
		'EC_R_INVALID_ARGUMENT',
		'EC_R_INVALID_B',
		'EC_R_INVALID_COFACTOR',
		'EC_R_INVALID_COMPRESSED_POINT',
		'EC_R_INVALID_COMPRESSION_BIT',
		'EC_R_INVALID_CURVE',
		'EC_R_INVALID_DIGEST',
		'EC_R_INVALID_DIGEST_TYPE',
		'EC_R_INVALID_ENCODING',
		'EC_R_INVALID_FIELD',
		'EC_R_INVALID_FORM',
		'EC_R_INVALID_GENERATOR',
		'EC_R_INVALID_GROUP_ORDER',
		'EC_R_INVALID_KEY',
		'EC_R_INVALID_LENGTH',
		'EC_R_INVALID_NAMED_GROUP_CONVERSION',
		'EC_R_INVALID_OUTPUT_LENGTH',
		'EC_R_INVALID_P',
		'EC_R_INVALID_PEER_KEY',
		'EC_R_INVALID_PENTANOMIAL_BASIS',
		'EC_R_INVALID_PRIVATE_KEY',
		'EC_R_INVALID_SEED',
		'EC_R_INVALID_TRINOMIAL_BASIS',
		'EC_R_KDF_PARAMETER_ERROR',
		'EC_R_KEYS_NOT_SET',
		'EC_R_LADDER_POST_FAILURE',
		'EC_R_LADDER_PRE_FAILURE',
		'EC_R_LADDER_STEP_FAILURE',
		'EC_R_MISSING_OID',
		'EC_R_MISSING_PARAMETERS',
		'EC_R_MISSING_PRIVATE_KEY',
		'EC_R_NEED_NEW_SETUP_VALUES',
		'EC_R_NOT_A_NIST_PRIME',
		'EC_R_NOT_IMPLEMENTED',
		'EC_R_NOT_INITIALIZED',
		'EC_R_NO_PARAMETERS_SET',
		'EC_R_NO_PRIVATE_VALUE',
		'EC_R_OPERATION_NOT_SUPPORTED',
		'EC_R_PASSED_NULL_PARAMETER',
		'EC_R_PEER_KEY_ERROR',
		'EC_R_POINT_ARITHMETIC_FAILURE',
		'EC_R_POINT_AT_INFINITY',
		'EC_R_POINT_COORDINATES_BLIND_FAILURE',
		'EC_R_POINT_IS_NOT_ON_CURVE',
		'EC_R_RANDOM_NUMBER_GENERATION_FAILED',
		'EC_R_SHARED_INFO_ERROR',
		'EC_R_SLOT_FULL',
		'EC_R_TOO_MANY_RETRIES',
		'EC_R_UNDEFINED_GENERATOR',
		'EC_R_UNDEFINED_ORDER',
		'EC_R_UNKNOWN_COFACTOR',
		'EC_R_UNKNOWN_GROUP',
		'EC_R_UNKNOWN_ORDER',
		'EC_R_UNSUPPORTED_FIELD',
		'EC_R_WRONG_CURVE_PARAMETERS',
		'EC_R_WRONG_ORDER'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_ASN1_ERROR [

	^ EC_R_ASN1_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_BAD_SIGNATURE [

	^ EC_R_BAD_SIGNATURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_BIGNUM_OUT_OF_RANGE [

	^ EC_R_BIGNUM_OUT_OF_RANGE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_BUFFER_TOO_SMALL [

	^ EC_R_BUFFER_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_CANNOT_INVERT [

	^ EC_R_CANNOT_INVERT
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_COORDINATES_OUT_OF_RANGE [

	^ EC_R_COORDINATES_OUT_OF_RANGE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_CURVE_DOES_NOT_SUPPORT_ECDH [

	^ EC_R_CURVE_DOES_NOT_SUPPORT_ECDH
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_CURVE_DOES_NOT_SUPPORT_ECDSA [

	^ EC_R_CURVE_DOES_NOT_SUPPORT_ECDSA
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING [

	^ EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_DECODE_ERROR [

	^ EC_R_DECODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_DISCRIMINANT_IS_ZERO [

	^ EC_R_DISCRIMINANT_IS_ZERO
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_EC_GROUP_NEW_BY_NAME_FAILURE [

	^ EC_R_EC_GROUP_NEW_BY_NAME_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_EXPLICIT_PARAMS_NOT_SUPPORTED [

	^ EC_R_EXPLICIT_PARAMS_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_FAILED_MAKING_PUBLIC_KEY [

	^ EC_R_FAILED_MAKING_PUBLIC_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_FIELD_TOO_LARGE [

	^ EC_R_FIELD_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_GF2M_NOT_SUPPORTED [

	^ EC_R_GF2M_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_GROUP2PKPARAMETERS_FAILURE [

	^ EC_R_GROUP2PKPARAMETERS_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_I2D_ECPKPARAMETERS_FAILURE [

	^ EC_R_I2D_ECPKPARAMETERS_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INCOMPATIBLE_OBJECTS [

	^ EC_R_INCOMPATIBLE_OBJECTS
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_A [

	^ EC_R_INVALID_A
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_ARGUMENT [

	^ EC_R_INVALID_ARGUMENT
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_B [

	^ EC_R_INVALID_B
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_COFACTOR [

	^ EC_R_INVALID_COFACTOR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_COMPRESSED_POINT [

	^ EC_R_INVALID_COMPRESSED_POINT
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_COMPRESSION_BIT [

	^ EC_R_INVALID_COMPRESSION_BIT
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_CURVE [

	^ EC_R_INVALID_CURVE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_DIGEST [

	^ EC_R_INVALID_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_DIGEST_TYPE [

	^ EC_R_INVALID_DIGEST_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_ENCODING [

	^ EC_R_INVALID_ENCODING
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_FIELD [

	^ EC_R_INVALID_FIELD
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_FORM [

	^ EC_R_INVALID_FORM
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_GENERATOR [

	^ EC_R_INVALID_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_GROUP_ORDER [

	^ EC_R_INVALID_GROUP_ORDER
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_KEY [

	^ EC_R_INVALID_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_LENGTH [

	^ EC_R_INVALID_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_NAMED_GROUP_CONVERSION [

	^ EC_R_INVALID_NAMED_GROUP_CONVERSION
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_OUTPUT_LENGTH [

	^ EC_R_INVALID_OUTPUT_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_P [

	^ EC_R_INVALID_P
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_PEER_KEY [

	^ EC_R_INVALID_PEER_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_PENTANOMIAL_BASIS [

	^ EC_R_INVALID_PENTANOMIAL_BASIS
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_PRIVATE_KEY [

	^ EC_R_INVALID_PRIVATE_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_SEED [

	^ EC_R_INVALID_SEED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_INVALID_TRINOMIAL_BASIS [

	^ EC_R_INVALID_TRINOMIAL_BASIS
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_KDF_PARAMETER_ERROR [

	^ EC_R_KDF_PARAMETER_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_KEYS_NOT_SET [

	^ EC_R_KEYS_NOT_SET
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_LADDER_POST_FAILURE [

	^ EC_R_LADDER_POST_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_LADDER_PRE_FAILURE [

	^ EC_R_LADDER_PRE_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_LADDER_STEP_FAILURE [

	^ EC_R_LADDER_STEP_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_MISSING_OID [

	^ EC_R_MISSING_OID
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_MISSING_PARAMETERS [

	^ EC_R_MISSING_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_MISSING_PRIVATE_KEY [

	^ EC_R_MISSING_PRIVATE_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NEED_NEW_SETUP_VALUES [

	^ EC_R_NEED_NEW_SETUP_VALUES
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NOT_A_NIST_PRIME [

	^ EC_R_NOT_A_NIST_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NOT_IMPLEMENTED [

	^ EC_R_NOT_IMPLEMENTED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NOT_INITIALIZED [

	^ EC_R_NOT_INITIALIZED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NO_PARAMETERS_SET [

	^ EC_R_NO_PARAMETERS_SET
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_NO_PRIVATE_VALUE [

	^ EC_R_NO_PRIVATE_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_OPERATION_NOT_SUPPORTED [

	^ EC_R_OPERATION_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_PASSED_NULL_PARAMETER [

	^ EC_R_PASSED_NULL_PARAMETER
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_PEER_KEY_ERROR [

	^ EC_R_PEER_KEY_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_POINT_ARITHMETIC_FAILURE [

	^ EC_R_POINT_ARITHMETIC_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_POINT_AT_INFINITY [

	^ EC_R_POINT_AT_INFINITY
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_POINT_COORDINATES_BLIND_FAILURE [

	^ EC_R_POINT_COORDINATES_BLIND_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_POINT_IS_NOT_ON_CURVE [

	^ EC_R_POINT_IS_NOT_ON_CURVE
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_RANDOM_NUMBER_GENERATION_FAILED [

	^ EC_R_RANDOM_NUMBER_GENERATION_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_SHARED_INFO_ERROR [

	^ EC_R_SHARED_INFO_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_SLOT_FULL [

	^ EC_R_SLOT_FULL
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_TOO_MANY_RETRIES [

	^ EC_R_TOO_MANY_RETRIES
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNDEFINED_GENERATOR [

	^ EC_R_UNDEFINED_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNDEFINED_ORDER [

	^ EC_R_UNDEFINED_ORDER
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNKNOWN_COFACTOR [

	^ EC_R_UNKNOWN_COFACTOR
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNKNOWN_GROUP [

	^ EC_R_UNKNOWN_GROUP
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNKNOWN_ORDER [

	^ EC_R_UNKNOWN_ORDER
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_UNSUPPORTED_FIELD [

	^ EC_R_UNSUPPORTED_FIELD
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_WRONG_CURVE_PARAMETERS [

	^ EC_R_WRONG_CURVE_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsEcerr class >> EC_R_WRONG_ORDER [

	^ EC_R_WRONG_ORDER
]

{ #category : 'class initialization' }
SSLConstantsEcerr class >> initialize [

	EC_R_ASN1_ERROR := 16r73.
	EC_R_BAD_SIGNATURE := 16r9C.
	EC_R_BIGNUM_OUT_OF_RANGE := 16r90.
	EC_R_BUFFER_TOO_SMALL := 16r64.
	EC_R_CANNOT_INVERT := 16rA5.
	EC_R_COORDINATES_OUT_OF_RANGE := 16r92.
	EC_R_CURVE_DOES_NOT_SUPPORT_ECDH := 16rA0.
	EC_R_CURVE_DOES_NOT_SUPPORT_ECDSA := 16rAA.
	EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING := 16r9F.
	EC_R_DECODE_ERROR := 16r8E.
	EC_R_DISCRIMINANT_IS_ZERO := 16r76.
	EC_R_EC_GROUP_NEW_BY_NAME_FAILURE := 16r77.
	EC_R_EXPLICIT_PARAMS_NOT_SUPPORTED := 16r7F.
	EC_R_FAILED_MAKING_PUBLIC_KEY := 16rA6.
	EC_R_FIELD_TOO_LARGE := 16r8F.
	EC_R_GF2M_NOT_SUPPORTED := 16r93.
	EC_R_GROUP2PKPARAMETERS_FAILURE := 16r78.
	EC_R_I2D_ECPKPARAMETERS_FAILURE := 16r79.
	EC_R_INCOMPATIBLE_OBJECTS := 16r65.
	EC_R_INVALID_A := 16rA8.
	EC_R_INVALID_ARGUMENT := 16r70.
	EC_R_INVALID_B := 16rA9.
	EC_R_INVALID_COFACTOR := 16rAB.
	EC_R_INVALID_COMPRESSED_POINT := 16r6E.
	EC_R_INVALID_COMPRESSION_BIT := 16r6D.
	EC_R_INVALID_CURVE := 16r8D.
	EC_R_INVALID_DIGEST := 16r97.
	EC_R_INVALID_DIGEST_TYPE := 16r8A.
	EC_R_INVALID_ENCODING := 16r66.
	EC_R_INVALID_FIELD := 16r67.
	EC_R_INVALID_FORM := 16r68.
	EC_R_INVALID_GENERATOR := 16rAD.
	EC_R_INVALID_GROUP_ORDER := 16r7A.
	EC_R_INVALID_KEY := 16r74.
	EC_R_INVALID_LENGTH := 16r75.
	EC_R_INVALID_NAMED_GROUP_CONVERSION := 16rAE.
	EC_R_INVALID_OUTPUT_LENGTH := 16rA1.
	EC_R_INVALID_P := 16rAC.
	EC_R_INVALID_PEER_KEY := 16r85.
	EC_R_INVALID_PENTANOMIAL_BASIS := 16r84.
	EC_R_INVALID_PRIVATE_KEY := 16r7B.
	EC_R_INVALID_SEED := 16rAF.
	EC_R_INVALID_TRINOMIAL_BASIS := 16r89.
	EC_R_KDF_PARAMETER_ERROR := 16r94.
	EC_R_KEYS_NOT_SET := 16r8C.
	EC_R_LADDER_POST_FAILURE := 16r88.
	EC_R_LADDER_PRE_FAILURE := 16r99.
	EC_R_LADDER_STEP_FAILURE := 16rA2.
	EC_R_MISSING_OID := 16rA7.
	EC_R_MISSING_PARAMETERS := 16r7C.
	EC_R_MISSING_PRIVATE_KEY := 16r7D.
	EC_R_NEED_NEW_SETUP_VALUES := 16r9D.
	EC_R_NOT_A_NIST_PRIME := 16r87.
	EC_R_NOT_IMPLEMENTED := 16r7E.
	EC_R_NOT_INITIALIZED := 16r6F.
	EC_R_NO_PARAMETERS_SET := 16r8B.
	EC_R_NO_PRIVATE_VALUE := 16r9A.
	EC_R_OPERATION_NOT_SUPPORTED := 16r98.
	EC_R_PASSED_NULL_PARAMETER := 16r86.
	EC_R_PEER_KEY_ERROR := 16r95.
	EC_R_POINT_ARITHMETIC_FAILURE := 16r9B.
	EC_R_POINT_AT_INFINITY := 16r6A.
	EC_R_POINT_COORDINATES_BLIND_FAILURE := 16rA3.
	EC_R_POINT_IS_NOT_ON_CURVE := 16r6B.
	EC_R_RANDOM_NUMBER_GENERATION_FAILED := 16r9E.
	EC_R_SHARED_INFO_ERROR := 16r96.
	EC_R_SLOT_FULL := 16r6C.
	EC_R_TOO_MANY_RETRIES := 16rB0.
	EC_R_UNDEFINED_GENERATOR := 16r71.
	EC_R_UNDEFINED_ORDER := 16r80.
	EC_R_UNKNOWN_COFACTOR := 16rA4.
	EC_R_UNKNOWN_GROUP := 16r81.
	EC_R_UNKNOWN_ORDER := 16r72.
	EC_R_UNSUPPORTED_FIELD := 16r83.
	EC_R_WRONG_CURVE_PARAMETERS := 16r91.
	EC_R_WRONG_ORDER := 16r82
]
