Class {
	#name : 'SSLConstantsTserr',
	#superclass : 'SharedPool',
	#classVars : [
		'TS_R_BAD_PKCS7_TYPE',
		'TS_R_BAD_TYPE',
		'TS_R_CANNOT_LOAD_CERT',
		'TS_R_CANNOT_LOAD_KEY',
		'TS_R_CERTIFICATE_VERIFY_ERROR',
		'TS_R_COULD_NOT_SET_ENGINE',
		'TS_R_COULD_NOT_SET_TIME',
		'TS_R_DETACHED_CONTENT',
		'TS_R_ESS_ADD_SIGNING_CERT_ERROR',
		'TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR',
		'TS_R_ESS_SIGNING_CERTIFICATE_ERROR',
		'TS_R_INVALID_NULL_POINTER',
		'TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE',
		'TS_R_MESSAGE_IMPRINT_MISMATCH',
		'TS_R_NONCE_MISMATCH',
		'TS_R_NONCE_NOT_RETURNED',
		'TS_R_NO_CONTENT',
		'TS_R_NO_TIME_STAMP_TOKEN',
		'TS_R_PKCS7_ADD_SIGNATURE_ERROR',
		'TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR',
		'TS_R_PKCS7_TO_TS_TST_INFO_FAILED',
		'TS_R_POLICY_MISMATCH',
		'TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE',
		'TS_R_RESPONSE_SETUP_ERROR',
		'TS_R_SIGNATURE_FAILURE',
		'TS_R_THERE_MUST_BE_ONE_SIGNER',
		'TS_R_TIME_SYSCALL_ERROR',
		'TS_R_TOKEN_NOT_PRESENT',
		'TS_R_TOKEN_PRESENT',
		'TS_R_TSA_NAME_MISMATCH',
		'TS_R_TSA_UNTRUSTED',
		'TS_R_TST_INFO_SETUP_ERROR',
		'TS_R_TS_DATASIGN',
		'TS_R_UNACCEPTABLE_POLICY',
		'TS_R_UNSUPPORTED_MD_ALGORITHM',
		'TS_R_UNSUPPORTED_VERSION',
		'TS_R_VAR_BAD_VALUE',
		'TS_R_VAR_LOOKUP_FAILURE',
		'TS_R_WRONG_CONTENT_TYPE'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_BAD_PKCS7_TYPE [

	^ TS_R_BAD_PKCS7_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_BAD_TYPE [

	^ TS_R_BAD_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_CANNOT_LOAD_CERT [

	^ TS_R_CANNOT_LOAD_CERT
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_CANNOT_LOAD_KEY [

	^ TS_R_CANNOT_LOAD_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_CERTIFICATE_VERIFY_ERROR [

	^ TS_R_CERTIFICATE_VERIFY_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_COULD_NOT_SET_ENGINE [

	^ TS_R_COULD_NOT_SET_ENGINE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_COULD_NOT_SET_TIME [

	^ TS_R_COULD_NOT_SET_TIME
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_DETACHED_CONTENT [

	^ TS_R_DETACHED_CONTENT
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_ESS_ADD_SIGNING_CERT_ERROR [

	^ TS_R_ESS_ADD_SIGNING_CERT_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR [

	^ TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_ESS_SIGNING_CERTIFICATE_ERROR [

	^ TS_R_ESS_SIGNING_CERTIFICATE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_INVALID_NULL_POINTER [

	^ TS_R_INVALID_NULL_POINTER
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE [

	^ TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_MESSAGE_IMPRINT_MISMATCH [

	^ TS_R_MESSAGE_IMPRINT_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_NONCE_MISMATCH [

	^ TS_R_NONCE_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_NONCE_NOT_RETURNED [

	^ TS_R_NONCE_NOT_RETURNED
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_NO_CONTENT [

	^ TS_R_NO_CONTENT
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_NO_TIME_STAMP_TOKEN [

	^ TS_R_NO_TIME_STAMP_TOKEN
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_PKCS7_ADD_SIGNATURE_ERROR [

	^ TS_R_PKCS7_ADD_SIGNATURE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR [

	^ TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_PKCS7_TO_TS_TST_INFO_FAILED [

	^ TS_R_PKCS7_TO_TS_TST_INFO_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_POLICY_MISMATCH [

	^ TS_R_POLICY_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE [

	^ TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_RESPONSE_SETUP_ERROR [

	^ TS_R_RESPONSE_SETUP_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_SIGNATURE_FAILURE [

	^ TS_R_SIGNATURE_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_THERE_MUST_BE_ONE_SIGNER [

	^ TS_R_THERE_MUST_BE_ONE_SIGNER
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TIME_SYSCALL_ERROR [

	^ TS_R_TIME_SYSCALL_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TOKEN_NOT_PRESENT [

	^ TS_R_TOKEN_NOT_PRESENT
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TOKEN_PRESENT [

	^ TS_R_TOKEN_PRESENT
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TSA_NAME_MISMATCH [

	^ TS_R_TSA_NAME_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TSA_UNTRUSTED [

	^ TS_R_TSA_UNTRUSTED
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TST_INFO_SETUP_ERROR [

	^ TS_R_TST_INFO_SETUP_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_TS_DATASIGN [

	^ TS_R_TS_DATASIGN
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_UNACCEPTABLE_POLICY [

	^ TS_R_UNACCEPTABLE_POLICY
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_UNSUPPORTED_MD_ALGORITHM [

	^ TS_R_UNSUPPORTED_MD_ALGORITHM
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_UNSUPPORTED_VERSION [

	^ TS_R_UNSUPPORTED_VERSION
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_VAR_BAD_VALUE [

	^ TS_R_VAR_BAD_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_VAR_LOOKUP_FAILURE [

	^ TS_R_VAR_LOOKUP_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsTserr class >> TS_R_WRONG_CONTENT_TYPE [

	^ TS_R_WRONG_CONTENT_TYPE
]

{ #category : 'class initialization' }
SSLConstantsTserr class >> initialize [

	TS_R_BAD_PKCS7_TYPE := 16r84.
	TS_R_BAD_TYPE := 16r85.
	TS_R_CANNOT_LOAD_CERT := 16r89.
	TS_R_CANNOT_LOAD_KEY := 16r8A.
	TS_R_CERTIFICATE_VERIFY_ERROR := 16r64.
	TS_R_COULD_NOT_SET_ENGINE := 16r7F.
	TS_R_COULD_NOT_SET_TIME := 16r73.
	TS_R_DETACHED_CONTENT := 16r86.
	TS_R_ESS_ADD_SIGNING_CERT_ERROR := 16r74.
	TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR := 16r8B.
	TS_R_ESS_SIGNING_CERTIFICATE_ERROR := 16r65.
	TS_R_INVALID_NULL_POINTER := 16r66.
	TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE := 16r75.
	TS_R_MESSAGE_IMPRINT_MISMATCH := 16r67.
	TS_R_NONCE_MISMATCH := 16r68.
	TS_R_NONCE_NOT_RETURNED := 16r69.
	TS_R_NO_CONTENT := 16r6A.
	TS_R_NO_TIME_STAMP_TOKEN := 16r6B.
	TS_R_PKCS7_ADD_SIGNATURE_ERROR := 16r76.
	TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR := 16r77.
	TS_R_PKCS7_TO_TS_TST_INFO_FAILED := 16r81.
	TS_R_POLICY_MISMATCH := 16r6C.
	TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE := 16r78.
	TS_R_RESPONSE_SETUP_ERROR := 16r79.
	TS_R_SIGNATURE_FAILURE := 16r6D.
	TS_R_THERE_MUST_BE_ONE_SIGNER := 16r6E.
	TS_R_TIME_SYSCALL_ERROR := 16r7A.
	TS_R_TOKEN_NOT_PRESENT := 16r82.
	TS_R_TOKEN_PRESENT := 16r83.
	TS_R_TSA_NAME_MISMATCH := 16r6F.
	TS_R_TSA_UNTRUSTED := 16r70.
	TS_R_TST_INFO_SETUP_ERROR := 16r7B.
	TS_R_TS_DATASIGN := 16r7C.
	TS_R_UNACCEPTABLE_POLICY := 16r7D.
	TS_R_UNSUPPORTED_MD_ALGORITHM := 16r7E.
	TS_R_UNSUPPORTED_VERSION := 16r71.
	TS_R_VAR_BAD_VALUE := 16r87.
	TS_R_VAR_LOOKUP_FAILURE := 16r88.
	TS_R_WRONG_CONTENT_TYPE := 16r72
]
