Class {
	#name : 'SSLConstantsConferr',
	#superclass : 'SharedPool',
	#classVars : [
		'CONF_R_ERROR_LOADING_DSO',
		'CONF_R_INVALID_PRAGMA',
		'CONF_R_LIST_CANNOT_BE_NULL',
		'CONF_R_MANDATORY_BRACES_IN_VARIABLE_EXPANSION',
		'CONF_R_MISSING_CLOSE_SQUARE_BRACKET',
		'CONF_R_MISSING_EQUAL_SIGN',
		'CONF_R_MISSING_INIT_FUNCTION',
		'CONF_R_MODULE_INITIALIZATION_ERROR',
		'CONF_R_NO_CLOSE_BRACE',
		'CONF_R_NO_CONF',
		'CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE',
		'CONF_R_NO_SECTION',
		'CONF_R_NO_SUCH_FILE',
		'CONF_R_NO_VALUE',
		'CONF_R_NUMBER_TOO_LARGE',
		'CONF_R_OPENSSL_CONF_REFERENCES_MISSING_SECTION',
		'CONF_R_RECURSIVE_DIRECTORY_INCLUDE',
		'CONF_R_RECURSIVE_SECTION_REFERENCE',
		'CONF_R_RELATIVE_PATH',
		'CONF_R_SSL_COMMAND_SECTION_EMPTY',
		'CONF_R_SSL_COMMAND_SECTION_NOT_FOUND',
		'CONF_R_SSL_SECTION_EMPTY',
		'CONF_R_SSL_SECTION_NOT_FOUND',
		'CONF_R_UNABLE_TO_CREATE_NEW_SECTION',
		'CONF_R_UNKNOWN_MODULE_NAME',
		'CONF_R_VARIABLE_EXPANSION_TOO_LONG',
		'CONF_R_VARIABLE_HAS_NO_VALUE'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_ERROR_LOADING_DSO [

	^ CONF_R_ERROR_LOADING_DSO
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_INVALID_PRAGMA [

	^ CONF_R_INVALID_PRAGMA
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_LIST_CANNOT_BE_NULL [

	^ CONF_R_LIST_CANNOT_BE_NULL
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_MANDATORY_BRACES_IN_VARIABLE_EXPANSION [

	^ CONF_R_MANDATORY_BRACES_IN_VARIABLE_EXPANSION
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_MISSING_CLOSE_SQUARE_BRACKET [

	^ CONF_R_MISSING_CLOSE_SQUARE_BRACKET
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_MISSING_EQUAL_SIGN [

	^ CONF_R_MISSING_EQUAL_SIGN
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_MISSING_INIT_FUNCTION [

	^ CONF_R_MISSING_INIT_FUNCTION
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_MODULE_INITIALIZATION_ERROR [

	^ CONF_R_MODULE_INITIALIZATION_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_CLOSE_BRACE [

	^ CONF_R_NO_CLOSE_BRACE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_CONF [

	^ CONF_R_NO_CONF
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE [

	^ CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_SECTION [

	^ CONF_R_NO_SECTION
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_SUCH_FILE [

	^ CONF_R_NO_SUCH_FILE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NO_VALUE [

	^ CONF_R_NO_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_NUMBER_TOO_LARGE [

	^ CONF_R_NUMBER_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_OPENSSL_CONF_REFERENCES_MISSING_SECTION [

	^ CONF_R_OPENSSL_CONF_REFERENCES_MISSING_SECTION
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_RECURSIVE_DIRECTORY_INCLUDE [

	^ CONF_R_RECURSIVE_DIRECTORY_INCLUDE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_RECURSIVE_SECTION_REFERENCE [

	^ CONF_R_RECURSIVE_SECTION_REFERENCE
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_RELATIVE_PATH [

	^ CONF_R_RELATIVE_PATH
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_SSL_COMMAND_SECTION_EMPTY [

	^ CONF_R_SSL_COMMAND_SECTION_EMPTY
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_SSL_COMMAND_SECTION_NOT_FOUND [

	^ CONF_R_SSL_COMMAND_SECTION_NOT_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_SSL_SECTION_EMPTY [

	^ CONF_R_SSL_SECTION_EMPTY
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_SSL_SECTION_NOT_FOUND [

	^ CONF_R_SSL_SECTION_NOT_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_UNABLE_TO_CREATE_NEW_SECTION [

	^ CONF_R_UNABLE_TO_CREATE_NEW_SECTION
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_UNKNOWN_MODULE_NAME [

	^ CONF_R_UNKNOWN_MODULE_NAME
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_VARIABLE_EXPANSION_TOO_LONG [

	^ CONF_R_VARIABLE_EXPANSION_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsConferr class >> CONF_R_VARIABLE_HAS_NO_VALUE [

	^ CONF_R_VARIABLE_HAS_NO_VALUE
]

{ #category : 'class initialization' }
SSLConstantsConferr class >> initialize [

	CONF_R_ERROR_LOADING_DSO := 16r6E.
	CONF_R_INVALID_PRAGMA := 16r7A.
	CONF_R_LIST_CANNOT_BE_NULL := 16r73.
	CONF_R_MANDATORY_BRACES_IN_VARIABLE_EXPANSION := 16r7B.
	CONF_R_MISSING_CLOSE_SQUARE_BRACKET := 16r64.
	CONF_R_MISSING_EQUAL_SIGN := 16r65.
	CONF_R_MISSING_INIT_FUNCTION := 16r70.
	CONF_R_MODULE_INITIALIZATION_ERROR := 16r6D.
	CONF_R_NO_CLOSE_BRACE := 16r66.
	CONF_R_NO_CONF := 16r69.
	CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE := 16r6A.
	CONF_R_NO_SECTION := 16r6B.
	CONF_R_NO_SUCH_FILE := 16r72.
	CONF_R_NO_VALUE := 16r6C.
	CONF_R_NUMBER_TOO_LARGE := 16r79.
	CONF_R_OPENSSL_CONF_REFERENCES_MISSING_SECTION := 16r7C.
	CONF_R_RECURSIVE_DIRECTORY_INCLUDE := 16r6F.
	CONF_R_RECURSIVE_SECTION_REFERENCE := 16r7E.
	CONF_R_RELATIVE_PATH := 16r7D.
	CONF_R_SSL_COMMAND_SECTION_EMPTY := 16r75.
	CONF_R_SSL_COMMAND_SECTION_NOT_FOUND := 16r76.
	CONF_R_SSL_SECTION_EMPTY := 16r77.
	CONF_R_SSL_SECTION_NOT_FOUND := 16r78.
	CONF_R_UNABLE_TO_CREATE_NEW_SECTION := 16r67.
	CONF_R_UNKNOWN_MODULE_NAME := 16r71.
	CONF_R_VARIABLE_EXPANSION_TOO_LONG := 16r74.
	CONF_R_VARIABLE_HAS_NO_VALUE := 16r68
]
