Class {
	#name : 'SSLConstantsEngine',
	#superclass : 'SharedPool',
	#classVars : [
		'ENGINE_CMD_BASE',
		'ENGINE_CMD_FLAG_INTERNAL',
		'ENGINE_CMD_FLAG_NO_INPUT',
		'ENGINE_CMD_FLAG_NUMERIC',
		'ENGINE_CMD_FLAG_STRING',
		'ENGINE_CTRL_CHIL_NO_LOCKING',
		'ENGINE_CTRL_CHIL_SET_FORKCHECK',
		'ENGINE_CTRL_GET_CMD_FLAGS',
		'ENGINE_CTRL_GET_CMD_FROM_NAME',
		'ENGINE_CTRL_GET_DESC_FROM_CMD',
		'ENGINE_CTRL_GET_DESC_LEN_FROM_CMD',
		'ENGINE_CTRL_GET_FIRST_CMD_TYPE',
		'ENGINE_CTRL_GET_NAME_FROM_CMD',
		'ENGINE_CTRL_GET_NAME_LEN_FROM_CMD',
		'ENGINE_CTRL_GET_NEXT_CMD_TYPE',
		'ENGINE_CTRL_HAS_CTRL_FUNCTION',
		'ENGINE_CTRL_HUP',
		'ENGINE_CTRL_LOAD_CONFIGURATION',
		'ENGINE_CTRL_LOAD_SECTION',
		'ENGINE_CTRL_SET_CALLBACK_DATA',
		'ENGINE_CTRL_SET_LOGSTREAM',
		'ENGINE_CTRL_SET_PASSWORD_CALLBACK',
		'ENGINE_CTRL_SET_USER_INTERFACE',
		'ENGINE_FLAGS_BY_ID_COPY',
		'ENGINE_FLAGS_MANUAL_CMD_CTRL',
		'ENGINE_FLAGS_NO_REGISTER_ALL',
		'ENGINE_METHOD_ALL',
		'ENGINE_METHOD_CIPHERS',
		'ENGINE_METHOD_DH',
		'ENGINE_METHOD_DIGESTS',
		'ENGINE_METHOD_DSA',
		'ENGINE_METHOD_EC',
		'ENGINE_METHOD_NONE',
		'ENGINE_METHOD_PKEY_ASN1_METHS',
		'ENGINE_METHOD_PKEY_METHS',
		'ENGINE_METHOD_RAND',
		'ENGINE_METHOD_RSA',
		'ENGINE_TABLE_FLAG_NOINIT',
		'OSSL_DYNAMIC_OLDEST',
		'OSSL_DYNAMIC_VERSION'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CMD_BASE [

	^ ENGINE_CMD_BASE
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CMD_FLAG_INTERNAL [

	^ ENGINE_CMD_FLAG_INTERNAL
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CMD_FLAG_NO_INPUT [

	^ ENGINE_CMD_FLAG_NO_INPUT
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CMD_FLAG_NUMERIC [

	^ ENGINE_CMD_FLAG_NUMERIC
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CMD_FLAG_STRING [

	^ ENGINE_CMD_FLAG_STRING
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_CHIL_NO_LOCKING [

	^ ENGINE_CTRL_CHIL_NO_LOCKING
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_CHIL_SET_FORKCHECK [

	^ ENGINE_CTRL_CHIL_SET_FORKCHECK
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_CMD_FLAGS [

	^ ENGINE_CTRL_GET_CMD_FLAGS
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_CMD_FROM_NAME [

	^ ENGINE_CTRL_GET_CMD_FROM_NAME
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_DESC_FROM_CMD [

	^ ENGINE_CTRL_GET_DESC_FROM_CMD
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_DESC_LEN_FROM_CMD [

	^ ENGINE_CTRL_GET_DESC_LEN_FROM_CMD
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_FIRST_CMD_TYPE [

	^ ENGINE_CTRL_GET_FIRST_CMD_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_NAME_FROM_CMD [

	^ ENGINE_CTRL_GET_NAME_FROM_CMD
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_NAME_LEN_FROM_CMD [

	^ ENGINE_CTRL_GET_NAME_LEN_FROM_CMD
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_GET_NEXT_CMD_TYPE [

	^ ENGINE_CTRL_GET_NEXT_CMD_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_HAS_CTRL_FUNCTION [

	^ ENGINE_CTRL_HAS_CTRL_FUNCTION
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_HUP [

	^ ENGINE_CTRL_HUP
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_LOAD_CONFIGURATION [

	^ ENGINE_CTRL_LOAD_CONFIGURATION
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_LOAD_SECTION [

	^ ENGINE_CTRL_LOAD_SECTION
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_SET_CALLBACK_DATA [

	^ ENGINE_CTRL_SET_CALLBACK_DATA
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_SET_LOGSTREAM [

	^ ENGINE_CTRL_SET_LOGSTREAM
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_SET_PASSWORD_CALLBACK [

	^ ENGINE_CTRL_SET_PASSWORD_CALLBACK
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_CTRL_SET_USER_INTERFACE [

	^ ENGINE_CTRL_SET_USER_INTERFACE
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_FLAGS_BY_ID_COPY [

	^ ENGINE_FLAGS_BY_ID_COPY
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_FLAGS_MANUAL_CMD_CTRL [

	^ ENGINE_FLAGS_MANUAL_CMD_CTRL
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_FLAGS_NO_REGISTER_ALL [

	^ ENGINE_FLAGS_NO_REGISTER_ALL
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_ALL [

	^ ENGINE_METHOD_ALL
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_CIPHERS [

	^ ENGINE_METHOD_CIPHERS
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_DH [

	^ ENGINE_METHOD_DH
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_DIGESTS [

	^ ENGINE_METHOD_DIGESTS
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_DSA [

	^ ENGINE_METHOD_DSA
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_EC [

	^ ENGINE_METHOD_EC
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_NONE [

	^ ENGINE_METHOD_NONE
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_PKEY_ASN1_METHS [

	^ ENGINE_METHOD_PKEY_ASN1_METHS
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_PKEY_METHS [

	^ ENGINE_METHOD_PKEY_METHS
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_RAND [

	^ ENGINE_METHOD_RAND
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_METHOD_RSA [

	^ ENGINE_METHOD_RSA
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> ENGINE_TABLE_FLAG_NOINIT [

	^ ENGINE_TABLE_FLAG_NOINIT
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> OSSL_DYNAMIC_OLDEST [

	^ OSSL_DYNAMIC_OLDEST
]

{ #category : 'accessing - constants' }
SSLConstantsEngine class >> OSSL_DYNAMIC_VERSION [

	^ OSSL_DYNAMIC_VERSION
]

{ #category : 'class initialization' }
SSLConstantsEngine class >> initialize [

	ENGINE_METHOD_RSA := 1	 "(unsigned int)0x0001".
	ENGINE_METHOD_DSA := 2	 "(unsigned int)0x0002".
	ENGINE_METHOD_DH := 4	 "(unsigned int)0x0004".
	ENGINE_METHOD_RAND := 8	 "(unsigned int)0x0008".
	ENGINE_METHOD_CIPHERS := 16r40	 "(unsigned int)0x0040".
	ENGINE_METHOD_DIGESTS := 16r80	 "(unsigned int)0x0080".
	ENGINE_METHOD_PKEY_METHS := 16r200	 "(unsigned int)0x0200".
	ENGINE_METHOD_PKEY_ASN1_METHS := 16r400	 "(unsigned int)0x0400".
	ENGINE_METHOD_EC := 16r800	 "(unsigned int)0x0800".
	ENGINE_METHOD_ALL := 16rFFFF	 "(unsigned int)0xFFFF".
	ENGINE_METHOD_NONE := 0	 "(unsigned int)0x0000".
	ENGINE_TABLE_FLAG_NOINIT := 1	 "(unsigned int)0x0001".
	ENGINE_FLAGS_MANUAL_CMD_CTRL := 2	 "(int)0x0002".
	ENGINE_FLAGS_BY_ID_COPY := 4	 "(int)0x0004".
	ENGINE_FLAGS_NO_REGISTER_ALL := 8	 "(int)0x0008".
	ENGINE_CMD_FLAG_NUMERIC := 1	 "(unsigned int)0x0001".
	ENGINE_CMD_FLAG_STRING := 2	 "(unsigned int)0x0002".
	ENGINE_CMD_FLAG_NO_INPUT := 4	 "(unsigned int)0x0004".
	ENGINE_CMD_FLAG_INTERNAL := 8	 "(unsigned int)0x0008".
	ENGINE_CTRL_SET_LOGSTREAM := 1.
	ENGINE_CTRL_SET_PASSWORD_CALLBACK := 2.
	ENGINE_CTRL_HUP := 3.
	ENGINE_CTRL_SET_USER_INTERFACE := 4.
	ENGINE_CTRL_SET_CALLBACK_DATA := 5.
	ENGINE_CTRL_LOAD_CONFIGURATION := 6.
	ENGINE_CTRL_LOAD_SECTION := 7.
	ENGINE_CTRL_HAS_CTRL_FUNCTION := 10.
	ENGINE_CTRL_GET_FIRST_CMD_TYPE := 11.
	ENGINE_CTRL_GET_NEXT_CMD_TYPE := 12.
	ENGINE_CTRL_GET_CMD_FROM_NAME := 13.
	ENGINE_CTRL_GET_NAME_LEN_FROM_CMD := 14.
	ENGINE_CTRL_GET_NAME_FROM_CMD := 15.
	ENGINE_CTRL_GET_DESC_LEN_FROM_CMD := 16r10.
	ENGINE_CTRL_GET_DESC_FROM_CMD := 16r11.
	ENGINE_CTRL_GET_CMD_FLAGS := 16r12.
	ENGINE_CMD_BASE := 16rC8.
	ENGINE_CTRL_CHIL_SET_FORKCHECK := 16r64.
	ENGINE_CTRL_CHIL_NO_LOCKING := 16r65.
	OSSL_DYNAMIC_VERSION := 16r30000	 "(unsigned long)0x00030000".
	OSSL_DYNAMIC_OLDEST := 16r30000	 "(unsigned long)0x00030000"
]
