Class {
	#name : 'SSLConstantsRsaerr',
	#superclass : 'SharedPool',
	#classVars : [
		'RSA_R_ALGORITHM_MISMATCH',
		'RSA_R_BAD_E_VALUE',
		'RSA_R_BAD_FIXED_HEADER_DECRYPT',
		'RSA_R_BAD_PAD_BYTE_COUNT',
		'RSA_R_BAD_SIGNATURE',
		'RSA_R_BLOCK_TYPE_IS_NOT_01',
		'RSA_R_BLOCK_TYPE_IS_NOT_02',
		'RSA_R_DATA_GREATER_THAN_MOD_LEN',
		'RSA_R_DATA_TOO_LARGE',
		'RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE',
		'RSA_R_DATA_TOO_LARGE_FOR_MODULUS',
		'RSA_R_DATA_TOO_SMALL',
		'RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE',
		'RSA_R_DIGEST_DOES_NOT_MATCH',
		'RSA_R_DIGEST_NOT_ALLOWED',
		'RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY',
		'RSA_R_DMP1_NOT_CONGRUENT_TO_D',
		'RSA_R_DMQ1_NOT_CONGRUENT_TO_D',
		'RSA_R_D_E_NOT_CONGRUENT_TO_1',
		'RSA_R_FIRST_OCTET_INVALID',
		'RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE',
		'RSA_R_INVALID_DIGEST',
		'RSA_R_INVALID_DIGEST_LENGTH',
		'RSA_R_INVALID_HEADER',
		'RSA_R_INVALID_KEYPAIR',
		'RSA_R_INVALID_KEY_LENGTH',
		'RSA_R_INVALID_LABEL',
		'RSA_R_INVALID_LENGTH',
		'RSA_R_INVALID_MESSAGE_LENGTH',
		'RSA_R_INVALID_MGF1_MD',
		'RSA_R_INVALID_MODULUS',
		'RSA_R_INVALID_MULTI_PRIME_KEY',
		'RSA_R_INVALID_OAEP_PARAMETERS',
		'RSA_R_INVALID_PADDING',
		'RSA_R_INVALID_PADDING_MODE',
		'RSA_R_INVALID_PSS_PARAMETERS',
		'RSA_R_INVALID_PSS_SALTLEN',
		'RSA_R_INVALID_REQUEST',
		'RSA_R_INVALID_SALT_LENGTH',
		'RSA_R_INVALID_STRENGTH',
		'RSA_R_INVALID_TRAILER',
		'RSA_R_INVALID_X931_DIGEST',
		'RSA_R_IQMP_NOT_INVERSE_OF_Q',
		'RSA_R_KEY_PRIME_NUM_INVALID',
		'RSA_R_KEY_SIZE_TOO_SMALL',
		'RSA_R_LAST_OCTET_INVALID',
		'RSA_R_MGF1_DIGEST_NOT_ALLOWED',
		'RSA_R_MISSING_PRIVATE_KEY',
		'RSA_R_MODULUS_TOO_LARGE',
		'RSA_R_MP_COEFFICIENT_NOT_INVERSE_OF_R',
		'RSA_R_MP_EXPONENT_NOT_CONGRUENT_TO_D',
		'RSA_R_MP_R_NOT_PRIME',
		'RSA_R_NO_PUBLIC_EXPONENT',
		'RSA_R_NULL_BEFORE_BLOCK_MISSING',
		'RSA_R_N_DOES_NOT_EQUAL_PRODUCT_OF_PRIMES',
		'RSA_R_N_DOES_NOT_EQUAL_P_Q',
		'RSA_R_OAEP_DECODING_ERROR',
		'RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE',
		'RSA_R_PADDING_CHECK_FAILED',
		'RSA_R_PAIRWISE_TEST_FAILURE',
		'RSA_R_PKCS_DECODING_ERROR',
		'RSA_R_PSS_SALTLEN_TOO_SMALL',
		'RSA_R_PUB_EXPONENT_OUT_OF_RANGE',
		'RSA_R_P_NOT_PRIME',
		'RSA_R_Q_NOT_PRIME',
		'RSA_R_RANDOMNESS_SOURCE_STRENGTH_INSUFFICIENT',
		'RSA_R_RSA_OPERATIONS_NOT_SUPPORTED',
		'RSA_R_SLEN_CHECK_FAILED',
		'RSA_R_SLEN_RECOVERY_FAILED',
		'RSA_R_SSLV3_ROLLBACK_ATTACK',
		'RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD',
		'RSA_R_UNKNOWN_ALGORITHM_TYPE',
		'RSA_R_UNKNOWN_DIGEST',
		'RSA_R_UNKNOWN_MASK_DIGEST',
		'RSA_R_UNKNOWN_PADDING_TYPE',
		'RSA_R_UNSUPPORTED_ENCRYPTION_TYPE',
		'RSA_R_UNSUPPORTED_LABEL_SOURCE',
		'RSA_R_UNSUPPORTED_MASK_ALGORITHM',
		'RSA_R_UNSUPPORTED_MASK_PARAMETER',
		'RSA_R_UNSUPPORTED_SIGNATURE_TYPE',
		'RSA_R_VALUE_MISSING',
		'RSA_R_WRONG_SIGNATURE_LENGTH'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_ALGORITHM_MISMATCH [

	^ RSA_R_ALGORITHM_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BAD_E_VALUE [

	^ RSA_R_BAD_E_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BAD_FIXED_HEADER_DECRYPT [

	^ RSA_R_BAD_FIXED_HEADER_DECRYPT
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BAD_PAD_BYTE_COUNT [

	^ RSA_R_BAD_PAD_BYTE_COUNT
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BAD_SIGNATURE [

	^ RSA_R_BAD_SIGNATURE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BLOCK_TYPE_IS_NOT_01 [

	^ RSA_R_BLOCK_TYPE_IS_NOT_01
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_BLOCK_TYPE_IS_NOT_02 [

	^ RSA_R_BLOCK_TYPE_IS_NOT_02
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_GREATER_THAN_MOD_LEN [

	^ RSA_R_DATA_GREATER_THAN_MOD_LEN
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_TOO_LARGE [

	^ RSA_R_DATA_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE [

	^ RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_TOO_LARGE_FOR_MODULUS [

	^ RSA_R_DATA_TOO_LARGE_FOR_MODULUS
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_TOO_SMALL [

	^ RSA_R_DATA_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE [

	^ RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DIGEST_DOES_NOT_MATCH [

	^ RSA_R_DIGEST_DOES_NOT_MATCH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DIGEST_NOT_ALLOWED [

	^ RSA_R_DIGEST_NOT_ALLOWED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY [

	^ RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DMP1_NOT_CONGRUENT_TO_D [

	^ RSA_R_DMP1_NOT_CONGRUENT_TO_D
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_DMQ1_NOT_CONGRUENT_TO_D [

	^ RSA_R_DMQ1_NOT_CONGRUENT_TO_D
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_D_E_NOT_CONGRUENT_TO_1 [

	^ RSA_R_D_E_NOT_CONGRUENT_TO_1
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_FIRST_OCTET_INVALID [

	^ RSA_R_FIRST_OCTET_INVALID
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE [

	^ RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_DIGEST [

	^ RSA_R_INVALID_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_DIGEST_LENGTH [

	^ RSA_R_INVALID_DIGEST_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_HEADER [

	^ RSA_R_INVALID_HEADER
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_KEYPAIR [

	^ RSA_R_INVALID_KEYPAIR
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_KEY_LENGTH [

	^ RSA_R_INVALID_KEY_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_LABEL [

	^ RSA_R_INVALID_LABEL
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_LENGTH [

	^ RSA_R_INVALID_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_MESSAGE_LENGTH [

	^ RSA_R_INVALID_MESSAGE_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_MGF1_MD [

	^ RSA_R_INVALID_MGF1_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_MODULUS [

	^ RSA_R_INVALID_MODULUS
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_MULTI_PRIME_KEY [

	^ RSA_R_INVALID_MULTI_PRIME_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_OAEP_PARAMETERS [

	^ RSA_R_INVALID_OAEP_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_PADDING [

	^ RSA_R_INVALID_PADDING
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_PADDING_MODE [

	^ RSA_R_INVALID_PADDING_MODE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_PSS_PARAMETERS [

	^ RSA_R_INVALID_PSS_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_PSS_SALTLEN [

	^ RSA_R_INVALID_PSS_SALTLEN
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_REQUEST [

	^ RSA_R_INVALID_REQUEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_SALT_LENGTH [

	^ RSA_R_INVALID_SALT_LENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_STRENGTH [

	^ RSA_R_INVALID_STRENGTH
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_TRAILER [

	^ RSA_R_INVALID_TRAILER
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_INVALID_X931_DIGEST [

	^ RSA_R_INVALID_X931_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_IQMP_NOT_INVERSE_OF_Q [

	^ RSA_R_IQMP_NOT_INVERSE_OF_Q
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_KEY_PRIME_NUM_INVALID [

	^ RSA_R_KEY_PRIME_NUM_INVALID
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_KEY_SIZE_TOO_SMALL [

	^ RSA_R_KEY_SIZE_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_LAST_OCTET_INVALID [

	^ RSA_R_LAST_OCTET_INVALID
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MGF1_DIGEST_NOT_ALLOWED [

	^ RSA_R_MGF1_DIGEST_NOT_ALLOWED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MISSING_PRIVATE_KEY [

	^ RSA_R_MISSING_PRIVATE_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MODULUS_TOO_LARGE [

	^ RSA_R_MODULUS_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MP_COEFFICIENT_NOT_INVERSE_OF_R [

	^ RSA_R_MP_COEFFICIENT_NOT_INVERSE_OF_R
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MP_EXPONENT_NOT_CONGRUENT_TO_D [

	^ RSA_R_MP_EXPONENT_NOT_CONGRUENT_TO_D
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_MP_R_NOT_PRIME [

	^ RSA_R_MP_R_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_NO_PUBLIC_EXPONENT [

	^ RSA_R_NO_PUBLIC_EXPONENT
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_NULL_BEFORE_BLOCK_MISSING [

	^ RSA_R_NULL_BEFORE_BLOCK_MISSING
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_N_DOES_NOT_EQUAL_PRODUCT_OF_PRIMES [

	^ RSA_R_N_DOES_NOT_EQUAL_PRODUCT_OF_PRIMES
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_N_DOES_NOT_EQUAL_P_Q [

	^ RSA_R_N_DOES_NOT_EQUAL_P_Q
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_OAEP_DECODING_ERROR [

	^ RSA_R_OAEP_DECODING_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE [

	^ RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_PADDING_CHECK_FAILED [

	^ RSA_R_PADDING_CHECK_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_PAIRWISE_TEST_FAILURE [

	^ RSA_R_PAIRWISE_TEST_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_PKCS_DECODING_ERROR [

	^ RSA_R_PKCS_DECODING_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_PSS_SALTLEN_TOO_SMALL [

	^ RSA_R_PSS_SALTLEN_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_PUB_EXPONENT_OUT_OF_RANGE [

	^ RSA_R_PUB_EXPONENT_OUT_OF_RANGE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_P_NOT_PRIME [

	^ RSA_R_P_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_Q_NOT_PRIME [

	^ RSA_R_Q_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_RANDOMNESS_SOURCE_STRENGTH_INSUFFICIENT [

	^ RSA_R_RANDOMNESS_SOURCE_STRENGTH_INSUFFICIENT
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_RSA_OPERATIONS_NOT_SUPPORTED [

	^ RSA_R_RSA_OPERATIONS_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_SLEN_CHECK_FAILED [

	^ RSA_R_SLEN_CHECK_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_SLEN_RECOVERY_FAILED [

	^ RSA_R_SLEN_RECOVERY_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_SSLV3_ROLLBACK_ATTACK [

	^ RSA_R_SSLV3_ROLLBACK_ATTACK
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD [

	^ RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNKNOWN_ALGORITHM_TYPE [

	^ RSA_R_UNKNOWN_ALGORITHM_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNKNOWN_DIGEST [

	^ RSA_R_UNKNOWN_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNKNOWN_MASK_DIGEST [

	^ RSA_R_UNKNOWN_MASK_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNKNOWN_PADDING_TYPE [

	^ RSA_R_UNKNOWN_PADDING_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNSUPPORTED_ENCRYPTION_TYPE [

	^ RSA_R_UNSUPPORTED_ENCRYPTION_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNSUPPORTED_LABEL_SOURCE [

	^ RSA_R_UNSUPPORTED_LABEL_SOURCE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNSUPPORTED_MASK_ALGORITHM [

	^ RSA_R_UNSUPPORTED_MASK_ALGORITHM
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNSUPPORTED_MASK_PARAMETER [

	^ RSA_R_UNSUPPORTED_MASK_PARAMETER
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_UNSUPPORTED_SIGNATURE_TYPE [

	^ RSA_R_UNSUPPORTED_SIGNATURE_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_VALUE_MISSING [

	^ RSA_R_VALUE_MISSING
]

{ #category : 'accessing - constants' }
SSLConstantsRsaerr class >> RSA_R_WRONG_SIGNATURE_LENGTH [

	^ RSA_R_WRONG_SIGNATURE_LENGTH
]

{ #category : 'class initialization' }
SSLConstantsRsaerr class >> initialize [

	RSA_R_ALGORITHM_MISMATCH := 16r64.
	RSA_R_BAD_E_VALUE := 16r65.
	RSA_R_BAD_FIXED_HEADER_DECRYPT := 16r66.
	RSA_R_BAD_PAD_BYTE_COUNT := 16r67.
	RSA_R_BAD_SIGNATURE := 16r68.
	RSA_R_BLOCK_TYPE_IS_NOT_01 := 16r6A.
	RSA_R_BLOCK_TYPE_IS_NOT_02 := 16r6B.
	RSA_R_DATA_GREATER_THAN_MOD_LEN := 16r6C.
	RSA_R_DATA_TOO_LARGE := 16r6D.
	RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE := 16r6E.
	RSA_R_DATA_TOO_LARGE_FOR_MODULUS := 16r84.
	RSA_R_DATA_TOO_SMALL := 16r6F.
	RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE := 16r7A.
	RSA_R_DIGEST_DOES_NOT_MATCH := 16r9E.
	RSA_R_DIGEST_NOT_ALLOWED := 16r91.
	RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY := 16r70.
	RSA_R_DMP1_NOT_CONGRUENT_TO_D := 16r7C.
	RSA_R_DMQ1_NOT_CONGRUENT_TO_D := 16r7D.
	RSA_R_D_E_NOT_CONGRUENT_TO_1 := 16r7B.
	RSA_R_FIRST_OCTET_INVALID := 16r85.
	RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE := 16r90.
	RSA_R_INVALID_DIGEST := 16r9D.
	RSA_R_INVALID_DIGEST_LENGTH := 16r8F.
	RSA_R_INVALID_HEADER := 16r89.
	RSA_R_INVALID_KEYPAIR := 16rAB.
	RSA_R_INVALID_KEY_LENGTH := 16rAD.
	RSA_R_INVALID_LABEL := 16rA0.
	RSA_R_INVALID_LENGTH := 16rB5.
	RSA_R_INVALID_MESSAGE_LENGTH := 16r83.
	RSA_R_INVALID_MGF1_MD := 16r9C.
	RSA_R_INVALID_MODULUS := 16rAE.
	RSA_R_INVALID_MULTI_PRIME_KEY := 16rA7.
	RSA_R_INVALID_OAEP_PARAMETERS := 16rA1.
	RSA_R_INVALID_PADDING := 16r8A.
	RSA_R_INVALID_PADDING_MODE := 16r8D.
	RSA_R_INVALID_PSS_PARAMETERS := 16r95.
	RSA_R_INVALID_PSS_SALTLEN := 16r92.
	RSA_R_INVALID_REQUEST := 16rAF.
	RSA_R_INVALID_SALT_LENGTH := 16r96.
	RSA_R_INVALID_STRENGTH := 16rB0.
	RSA_R_INVALID_TRAILER := 16r8B.
	RSA_R_INVALID_X931_DIGEST := 16r8E.
	RSA_R_IQMP_NOT_INVERSE_OF_Q := 16r7E.
	RSA_R_KEY_PRIME_NUM_INVALID := 16rA5.
	RSA_R_KEY_SIZE_TOO_SMALL := 16r78.
	RSA_R_LAST_OCTET_INVALID := 16r86.
	RSA_R_MGF1_DIGEST_NOT_ALLOWED := 16r98.
	RSA_R_MISSING_PRIVATE_KEY := 16rB3.
	RSA_R_MODULUS_TOO_LARGE := 16r69.
	RSA_R_MP_COEFFICIENT_NOT_INVERSE_OF_R := 16rA8.
	RSA_R_MP_EXPONENT_NOT_CONGRUENT_TO_D := 16rA9.
	RSA_R_MP_R_NOT_PRIME := 16rAA.
	RSA_R_NO_PUBLIC_EXPONENT := 16r8C.
	RSA_R_NULL_BEFORE_BLOCK_MISSING := 16r71.
	RSA_R_N_DOES_NOT_EQUAL_PRODUCT_OF_PRIMES := 16rAC.
	RSA_R_N_DOES_NOT_EQUAL_P_Q := 16r7F.
	RSA_R_OAEP_DECODING_ERROR := 16r79.
	RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE := 16r94.
	RSA_R_PADDING_CHECK_FAILED := 16r72.
	RSA_R_PAIRWISE_TEST_FAILURE := 16rB1.
	RSA_R_PKCS_DECODING_ERROR := 16r9F.
	RSA_R_PSS_SALTLEN_TOO_SMALL := 16rA4.
	RSA_R_PUB_EXPONENT_OUT_OF_RANGE := 16rB2.
	RSA_R_P_NOT_PRIME := 16r80.
	RSA_R_Q_NOT_PRIME := 16r81.
	RSA_R_RANDOMNESS_SOURCE_STRENGTH_INSUFFICIENT := 16rB4.
	RSA_R_RSA_OPERATIONS_NOT_SUPPORTED := 16r82.
	RSA_R_SLEN_CHECK_FAILED := 16r88.
	RSA_R_SLEN_RECOVERY_FAILED := 16r87.
	RSA_R_SSLV3_ROLLBACK_ATTACK := 16r73.
	RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD := 16r74.
	RSA_R_UNKNOWN_ALGORITHM_TYPE := 16r75.
	RSA_R_UNKNOWN_DIGEST := 16rA6.
	RSA_R_UNKNOWN_MASK_DIGEST := 16r97.
	RSA_R_UNKNOWN_PADDING_TYPE := 16r76.
	RSA_R_UNSUPPORTED_ENCRYPTION_TYPE := 16rA2.
	RSA_R_UNSUPPORTED_LABEL_SOURCE := 16rA3.
	RSA_R_UNSUPPORTED_MASK_ALGORITHM := 16r99.
	RSA_R_UNSUPPORTED_MASK_PARAMETER := 16r9A.
	RSA_R_UNSUPPORTED_SIGNATURE_TYPE := 16r9B.
	RSA_R_VALUE_MISSING := 16r93.
	RSA_R_WRONG_SIGNATURE_LENGTH := 16r77
]
