Class {
	#name : 'SSLConstantsDh',
	#superclass : 'SharedPool',
	#classVars : [
		'DH_CHECK_INVALID_J_VALUE',
		'DH_CHECK_INVALID_Q_VALUE',
		'DH_CHECK_PUBKEY_INVALID',
		'DH_CHECK_PUBKEY_TOO_LARGE',
		'DH_CHECK_PUBKEY_TOO_SMALL',
		'DH_CHECK_P_NOT_PRIME',
		'DH_CHECK_P_NOT_SAFE_PRIME',
		'DH_CHECK_P_NOT_STRONG_PRIME',
		'DH_CHECK_Q_NOT_PRIME',
		'DH_FLAG_CACHE_MONT_P',
		'DH_FLAG_FIPS_METHOD',
		'DH_FLAG_NON_FIPS_ALLOW',
		'DH_FLAG_NO_EXP_CONSTTIME',
		'DH_FLAG_TYPE_DH',
		'DH_FLAG_TYPE_DHX',
		'DH_FLAG_TYPE_MASK',
		'DH_GENERATOR_2',
		'DH_GENERATOR_3',
		'DH_GENERATOR_5',
		'DH_MODULUS_TOO_LARGE',
		'DH_MODULUS_TOO_SMALL',
		'DH_NOT_SUITABLE_GENERATOR',
		'DH_PARAMGEN_TYPE_FIPS_186_2',
		'DH_PARAMGEN_TYPE_FIPS_186_4',
		'DH_PARAMGEN_TYPE_GENERATOR',
		'DH_PARAMGEN_TYPE_GROUP',
		'DH_UNABLE_TO_CHECK_GENERATOR',
		'EVP_PKEY_CTRL_DH_KDF_MD',
		'EVP_PKEY_CTRL_DH_KDF_OID',
		'EVP_PKEY_CTRL_DH_KDF_OUTLEN',
		'EVP_PKEY_CTRL_DH_KDF_TYPE',
		'EVP_PKEY_CTRL_DH_KDF_UKM',
		'EVP_PKEY_CTRL_DH_NID',
		'EVP_PKEY_CTRL_DH_PAD',
		'EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR',
		'EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN',
		'EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN',
		'EVP_PKEY_CTRL_DH_PARAMGEN_TYPE',
		'EVP_PKEY_CTRL_DH_RFC5114',
		'EVP_PKEY_CTRL_GET_DH_KDF_MD',
		'EVP_PKEY_CTRL_GET_DH_KDF_OID',
		'EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN',
		'EVP_PKEY_CTRL_GET_DH_KDF_UKM',
		'EVP_PKEY_DH_KDF_NONE',
		'EVP_PKEY_DH_KDF_X9_42',
		'OPENSSL_DH_CHECK_MAX_MODULUS_BITS',
		'OPENSSL_DH_FIPS_MIN_MODULUS_BITS',
		'OPENSSL_DH_MAX_MODULUS_BITS'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_INVALID_J_VALUE [

	^ DH_CHECK_INVALID_J_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_INVALID_Q_VALUE [

	^ DH_CHECK_INVALID_Q_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_PUBKEY_INVALID [

	^ DH_CHECK_PUBKEY_INVALID
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_PUBKEY_TOO_LARGE [

	^ DH_CHECK_PUBKEY_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_PUBKEY_TOO_SMALL [

	^ DH_CHECK_PUBKEY_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_P_NOT_PRIME [

	^ DH_CHECK_P_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_P_NOT_SAFE_PRIME [

	^ DH_CHECK_P_NOT_SAFE_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_P_NOT_STRONG_PRIME [

	^ DH_CHECK_P_NOT_STRONG_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_CHECK_Q_NOT_PRIME [

	^ DH_CHECK_Q_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_CACHE_MONT_P [

	^ DH_FLAG_CACHE_MONT_P
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_FIPS_METHOD [

	^ DH_FLAG_FIPS_METHOD
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_NON_FIPS_ALLOW [

	^ DH_FLAG_NON_FIPS_ALLOW
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_NO_EXP_CONSTTIME [

	^ DH_FLAG_NO_EXP_CONSTTIME
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_TYPE_DH [

	^ DH_FLAG_TYPE_DH
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_TYPE_DHX [

	^ DH_FLAG_TYPE_DHX
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_FLAG_TYPE_MASK [

	^ DH_FLAG_TYPE_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_GENERATOR_2 [

	^ DH_GENERATOR_2
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_GENERATOR_3 [

	^ DH_GENERATOR_3
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_GENERATOR_5 [

	^ DH_GENERATOR_5
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_MODULUS_TOO_LARGE [

	^ DH_MODULUS_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_MODULUS_TOO_SMALL [

	^ DH_MODULUS_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_NOT_SUITABLE_GENERATOR [

	^ DH_NOT_SUITABLE_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_PARAMGEN_TYPE_FIPS_186_2 [

	^ DH_PARAMGEN_TYPE_FIPS_186_2
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_PARAMGEN_TYPE_FIPS_186_4 [

	^ DH_PARAMGEN_TYPE_FIPS_186_4
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_PARAMGEN_TYPE_GENERATOR [

	^ DH_PARAMGEN_TYPE_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_PARAMGEN_TYPE_GROUP [

	^ DH_PARAMGEN_TYPE_GROUP
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> DH_UNABLE_TO_CHECK_GENERATOR [

	^ DH_UNABLE_TO_CHECK_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_KDF_MD [

	^ EVP_PKEY_CTRL_DH_KDF_MD
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_KDF_OID [

	^ EVP_PKEY_CTRL_DH_KDF_OID
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_KDF_OUTLEN [

	^ EVP_PKEY_CTRL_DH_KDF_OUTLEN
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_KDF_TYPE [

	^ EVP_PKEY_CTRL_DH_KDF_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_KDF_UKM [

	^ EVP_PKEY_CTRL_DH_KDF_UKM
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_NID [

	^ EVP_PKEY_CTRL_DH_NID
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_PAD [

	^ EVP_PKEY_CTRL_DH_PAD
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR [

	^ EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN [

	^ EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN [

	^ EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_PARAMGEN_TYPE [

	^ EVP_PKEY_CTRL_DH_PARAMGEN_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_DH_RFC5114 [

	^ EVP_PKEY_CTRL_DH_RFC5114
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_GET_DH_KDF_MD [

	^ EVP_PKEY_CTRL_GET_DH_KDF_MD
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_GET_DH_KDF_OID [

	^ EVP_PKEY_CTRL_GET_DH_KDF_OID
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN [

	^ EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_CTRL_GET_DH_KDF_UKM [

	^ EVP_PKEY_CTRL_GET_DH_KDF_UKM
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_DH_KDF_NONE [

	^ EVP_PKEY_DH_KDF_NONE
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> EVP_PKEY_DH_KDF_X9_42 [

	^ EVP_PKEY_DH_KDF_X9_42
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> OPENSSL_DH_CHECK_MAX_MODULUS_BITS [

	^ OPENSSL_DH_CHECK_MAX_MODULUS_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> OPENSSL_DH_FIPS_MIN_MODULUS_BITS [

	^ OPENSSL_DH_FIPS_MIN_MODULUS_BITS
]

{ #category : 'accessing - constants' }
SSLConstantsDh class >> OPENSSL_DH_MAX_MODULUS_BITS [

	^ OPENSSL_DH_MAX_MODULUS_BITS
]

{ #category : 'class initialization' }
SSLConstantsDh class >> initialize [

	DH_PARAMGEN_TYPE_GENERATOR := 0.
	DH_PARAMGEN_TYPE_FIPS_186_2 := 1.
	DH_PARAMGEN_TYPE_FIPS_186_4 := 2.
	DH_PARAMGEN_TYPE_GROUP := 3.
	EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN := 16r1001	 "(EVP_PKEY_ALG_CTRL + 1)".
	EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR := 16r1002	 "(EVP_PKEY_ALG_CTRL + 2)".
	EVP_PKEY_CTRL_DH_RFC5114 := 16r1003	 "(EVP_PKEY_ALG_CTRL + 3)".
	EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN := 16r1004	 "(EVP_PKEY_ALG_CTRL + 4)".
	EVP_PKEY_CTRL_DH_PARAMGEN_TYPE := 16r1005	 "(EVP_PKEY_ALG_CTRL + 5)".
	EVP_PKEY_CTRL_DH_KDF_TYPE := 16r1006	 "(EVP_PKEY_ALG_CTRL + 6)".
	EVP_PKEY_CTRL_DH_KDF_MD := 16r1007	 "(EVP_PKEY_ALG_CTRL + 7)".
	EVP_PKEY_CTRL_GET_DH_KDF_MD := 16r1008	 "(EVP_PKEY_ALG_CTRL + 8)".
	EVP_PKEY_CTRL_DH_KDF_OUTLEN := 16r1009	 "(EVP_PKEY_ALG_CTRL + 9)".
	EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN := 16r100A	 "(EVP_PKEY_ALG_CTRL + 10)".
	EVP_PKEY_CTRL_DH_KDF_UKM := 16r100B	 "(EVP_PKEY_ALG_CTRL + 11)".
	EVP_PKEY_CTRL_GET_DH_KDF_UKM := 16r100C	 "(EVP_PKEY_ALG_CTRL + 12)".
	EVP_PKEY_CTRL_DH_KDF_OID := 16r100D	 "(EVP_PKEY_ALG_CTRL + 13)".
	EVP_PKEY_CTRL_GET_DH_KDF_OID := 16r100E	 "(EVP_PKEY_ALG_CTRL + 14)".
	EVP_PKEY_CTRL_DH_NID := 16r100F	 "(EVP_PKEY_ALG_CTRL + 15)".
	EVP_PKEY_CTRL_DH_PAD := 16r1010	 "(EVP_PKEY_ALG_CTRL + 16)".
	EVP_PKEY_DH_KDF_NONE := 1.
	EVP_PKEY_DH_KDF_X9_42 := 2.
	OPENSSL_DH_MAX_MODULUS_BITS := 16r2710.
	OPENSSL_DH_CHECK_MAX_MODULUS_BITS := 16r8000.
	OPENSSL_DH_FIPS_MIN_MODULUS_BITS := 16r400.
	DH_FLAG_CACHE_MONT_P := 16r01.
	DH_FLAG_TYPE_MASK := 16rF000.
	DH_FLAG_TYPE_DH := 16r0000.
	DH_FLAG_TYPE_DHX := 16r1000.
	DH_FLAG_NO_EXP_CONSTTIME := 16r00.
	DH_FLAG_FIPS_METHOD := 16r0400.
	DH_FLAG_NON_FIPS_ALLOW := 16r0400.
	DH_GENERATOR_2 := 2.
	DH_GENERATOR_3 := 3.
	DH_GENERATOR_5 := 5.
	DH_CHECK_P_NOT_PRIME := 16r01.
	DH_CHECK_P_NOT_SAFE_PRIME := 16r02.
	DH_UNABLE_TO_CHECK_GENERATOR := 16r04.
	DH_NOT_SUITABLE_GENERATOR := 16r08.
	DH_CHECK_Q_NOT_PRIME := 16r10.
	DH_CHECK_INVALID_Q_VALUE := 16r20.
	DH_CHECK_INVALID_J_VALUE := 16r40.
	DH_MODULUS_TOO_SMALL := 16r80.
	DH_MODULUS_TOO_LARGE := 16r100.
	DH_CHECK_PUBKEY_TOO_SMALL := 16r01.
	DH_CHECK_PUBKEY_TOO_LARGE := 16r02.
	DH_CHECK_PUBKEY_INVALID := 16r04.
	DH_CHECK_P_NOT_STRONG_PRIME := 2	 "DH_CHECK_P_NOT_SAFE_PRIME"
]
