Class {
	#name : 'SSLConstantsX509',
	#superclass : 'SharedPool',
	#classVars : [
		'X509_ADD_FLAG_DEFAULT',
		'X509_ADD_FLAG_NO_DUP',
		'X509_ADD_FLAG_NO_SS',
		'X509_ADD_FLAG_PREPEND',
		'X509_ADD_FLAG_UP_REF',
		'X509_CRL_VERSION_1',
		'X509_CRL_VERSION_2',
		'X509_EXT_PACK_STRING',
		'X509_EXT_PACK_UNKNOWN',
		'X509_EX_V_INIT',
		'X509_EX_V_NETSCAPE_HACK',
		'X509_FILETYPE_ASN1',
		'X509_FILETYPE_DEFAULT',
		'X509_FILETYPE_PEM',
		'X509_FLAG_COMPAT',
		'X509_FLAG_EXTENSIONS_ONLY_KID',
		'X509_FLAG_NO_ATTRIBUTES',
		'X509_FLAG_NO_AUX',
		'X509_FLAG_NO_EXTENSIONS',
		'X509_FLAG_NO_HEADER',
		'X509_FLAG_NO_IDS',
		'X509_FLAG_NO_ISSUER',
		'X509_FLAG_NO_PUBKEY',
		'X509_FLAG_NO_SERIAL',
		'X509_FLAG_NO_SIGDUMP',
		'X509_FLAG_NO_SIGNAME',
		'X509_FLAG_NO_SUBJECT',
		'X509_FLAG_NO_VALIDITY',
		'X509_FLAG_NO_VERSION',
		'X509_REQ_VERSION_1',
		'X509_SIG_INFO_TLS',
		'X509_SIG_INFO_VALID',
		'X509_VERSION_1',
		'X509_VERSION_2',
		'X509_VERSION_3',
		'X509v3_KU_CRL_SIGN',
		'X509v3_KU_DATA_ENCIPHERMENT',
		'X509v3_KU_DECIPHER_ONLY',
		'X509v3_KU_DIGITAL_SIGNATURE',
		'X509v3_KU_ENCIPHER_ONLY',
		'X509v3_KU_KEY_AGREEMENT',
		'X509v3_KU_KEY_CERT_SIGN',
		'X509v3_KU_KEY_ENCIPHERMENT',
		'X509v3_KU_NON_REPUDIATION',
		'X509v3_KU_UNDEF',
		'XN_FLAG_COMPAT',
		'XN_FLAG_DN_REV',
		'XN_FLAG_DUMP_UNKNOWN_FIELDS',
		'XN_FLAG_FN_ALIGN',
		'XN_FLAG_FN_LN',
		'XN_FLAG_FN_MASK',
		'XN_FLAG_FN_NONE',
		'XN_FLAG_FN_OID',
		'XN_FLAG_FN_SN',
		'XN_FLAG_MULTILINE',
		'XN_FLAG_ONELINE',
		'XN_FLAG_RFC2253',
		'XN_FLAG_SEP_COMMA_PLUS',
		'XN_FLAG_SEP_CPLUS_SPC',
		'XN_FLAG_SEP_MASK',
		'XN_FLAG_SEP_MULTILINE',
		'XN_FLAG_SEP_SPLUS_SPC',
		'XN_FLAG_SPC_EQ'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_ADD_FLAG_DEFAULT [

	^ X509_ADD_FLAG_DEFAULT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_ADD_FLAG_NO_DUP [

	^ X509_ADD_FLAG_NO_DUP
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_ADD_FLAG_NO_SS [

	^ X509_ADD_FLAG_NO_SS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_ADD_FLAG_PREPEND [

	^ X509_ADD_FLAG_PREPEND
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_ADD_FLAG_UP_REF [

	^ X509_ADD_FLAG_UP_REF
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_CRL_VERSION_1 [

	^ X509_CRL_VERSION_1
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_CRL_VERSION_2 [

	^ X509_CRL_VERSION_2
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_EXT_PACK_STRING [

	^ X509_EXT_PACK_STRING
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_EXT_PACK_UNKNOWN [

	^ X509_EXT_PACK_UNKNOWN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_EX_V_INIT [

	^ X509_EX_V_INIT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_EX_V_NETSCAPE_HACK [

	^ X509_EX_V_NETSCAPE_HACK
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FILETYPE_ASN1 [

	^ X509_FILETYPE_ASN1
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FILETYPE_DEFAULT [

	^ X509_FILETYPE_DEFAULT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FILETYPE_PEM [

	^ X509_FILETYPE_PEM
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_COMPAT [

	^ X509_FLAG_COMPAT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_EXTENSIONS_ONLY_KID [

	^ X509_FLAG_EXTENSIONS_ONLY_KID
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_ATTRIBUTES [

	^ X509_FLAG_NO_ATTRIBUTES
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_AUX [

	^ X509_FLAG_NO_AUX
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_EXTENSIONS [

	^ X509_FLAG_NO_EXTENSIONS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_HEADER [

	^ X509_FLAG_NO_HEADER
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_IDS [

	^ X509_FLAG_NO_IDS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_ISSUER [

	^ X509_FLAG_NO_ISSUER
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_PUBKEY [

	^ X509_FLAG_NO_PUBKEY
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_SERIAL [

	^ X509_FLAG_NO_SERIAL
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_SIGDUMP [

	^ X509_FLAG_NO_SIGDUMP
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_SIGNAME [

	^ X509_FLAG_NO_SIGNAME
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_SUBJECT [

	^ X509_FLAG_NO_SUBJECT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_VALIDITY [

	^ X509_FLAG_NO_VALIDITY
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_FLAG_NO_VERSION [

	^ X509_FLAG_NO_VERSION
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_REQ_VERSION_1 [

	^ X509_REQ_VERSION_1
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_SIG_INFO_TLS [

	^ X509_SIG_INFO_TLS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_SIG_INFO_VALID [

	^ X509_SIG_INFO_VALID
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_VERSION_1 [

	^ X509_VERSION_1
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_VERSION_2 [

	^ X509_VERSION_2
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509_VERSION_3 [

	^ X509_VERSION_3
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_CRL_SIGN [

	^ X509v3_KU_CRL_SIGN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_DATA_ENCIPHERMENT [

	^ X509v3_KU_DATA_ENCIPHERMENT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_DECIPHER_ONLY [

	^ X509v3_KU_DECIPHER_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_DIGITAL_SIGNATURE [

	^ X509v3_KU_DIGITAL_SIGNATURE
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_ENCIPHER_ONLY [

	^ X509v3_KU_ENCIPHER_ONLY
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_KEY_AGREEMENT [

	^ X509v3_KU_KEY_AGREEMENT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_KEY_CERT_SIGN [

	^ X509v3_KU_KEY_CERT_SIGN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_KEY_ENCIPHERMENT [

	^ X509v3_KU_KEY_ENCIPHERMENT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_NON_REPUDIATION [

	^ X509v3_KU_NON_REPUDIATION
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> X509v3_KU_UNDEF [

	^ X509v3_KU_UNDEF
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_COMPAT [

	^ XN_FLAG_COMPAT
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_DN_REV [

	^ XN_FLAG_DN_REV
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_DUMP_UNKNOWN_FIELDS [

	^ XN_FLAG_DUMP_UNKNOWN_FIELDS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_ALIGN [

	^ XN_FLAG_FN_ALIGN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_LN [

	^ XN_FLAG_FN_LN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_MASK [

	^ XN_FLAG_FN_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_NONE [

	^ XN_FLAG_FN_NONE
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_OID [

	^ XN_FLAG_FN_OID
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_FN_SN [

	^ XN_FLAG_FN_SN
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_MULTILINE [

	^ XN_FLAG_MULTILINE
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_ONELINE [

	^ XN_FLAG_ONELINE
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_RFC2253 [

	^ XN_FLAG_RFC2253
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SEP_COMMA_PLUS [

	^ XN_FLAG_SEP_COMMA_PLUS
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SEP_CPLUS_SPC [

	^ XN_FLAG_SEP_CPLUS_SPC
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SEP_MASK [

	^ XN_FLAG_SEP_MASK
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SEP_MULTILINE [

	^ XN_FLAG_SEP_MULTILINE
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SEP_SPLUS_SPC [

	^ XN_FLAG_SEP_SPLUS_SPC
]

{ #category : 'accessing - constants' }
SSLConstantsX509 class >> XN_FLAG_SPC_EQ [

	^ XN_FLAG_SPC_EQ
]

{ #category : 'class initialization' }
SSLConstantsX509 class >> initialize [

	X509_SIG_INFO_VALID := 16r1.
	X509_SIG_INFO_TLS := 16r2.
	X509_FILETYPE_PEM := 1.
	X509_FILETYPE_ASN1 := 2.
	X509_FILETYPE_DEFAULT := 3.
	X509v3_KU_DIGITAL_SIGNATURE := 16r0080.
	X509v3_KU_NON_REPUDIATION := 16r0040.
	X509v3_KU_KEY_ENCIPHERMENT := 16r0020.
	X509v3_KU_DATA_ENCIPHERMENT := 16r0010.
	X509v3_KU_KEY_AGREEMENT := 16r0008.
	X509v3_KU_KEY_CERT_SIGN := 16r0004.
	X509v3_KU_CRL_SIGN := 16r0002.
	X509v3_KU_ENCIPHER_ONLY := 16r0001.
	X509v3_KU_DECIPHER_ONLY := 16r8000.
	X509v3_KU_UNDEF := 16rffff.
	X509_EX_V_NETSCAPE_HACK := 16r8000.
	X509_EX_V_INIT := 16r0001.
	X509_FLAG_COMPAT := 0.
	X509_FLAG_NO_HEADER := 1.
	X509_FLAG_NO_VERSION := 2	 "(1L << 1)".
	X509_FLAG_NO_SERIAL := 4	 "(1L << 2)".
	X509_FLAG_NO_SIGNAME := 8	 "(1L << 3)".
	X509_FLAG_NO_ISSUER := 16r10	 "(1L << 4)".
	X509_FLAG_NO_VALIDITY := 16r20	 "(1L << 5)".
	X509_FLAG_NO_SUBJECT := 16r40	 "(1L << 6)".
	X509_FLAG_NO_PUBKEY := 16r80	 "(1L << 7)".
	X509_FLAG_NO_EXTENSIONS := 16r100	 "(1L << 8)".
	X509_FLAG_NO_SIGDUMP := 16r200	 "(1L << 9)".
	X509_FLAG_NO_AUX := 16r400	 "(1L << 10)".
	X509_FLAG_NO_ATTRIBUTES := 16r800	 "(1L << 11)".
	X509_FLAG_NO_IDS := 16r1000	 "(1L << 12)".
	X509_FLAG_EXTENSIONS_ONLY_KID := 16r2000	 "(1L << 13)".
	XN_FLAG_SEP_MASK := 16rF0000	 "(0xf << 16)".
	XN_FLAG_COMPAT := 0.
	XN_FLAG_SEP_COMMA_PLUS := 16r10000	 "(1 << 16)".
	XN_FLAG_SEP_CPLUS_SPC := 16r20000	 "(2 << 16)".
	XN_FLAG_SEP_SPLUS_SPC := 16r30000	 "(3 << 16)".
	XN_FLAG_SEP_MULTILINE := 16r40000	 "(4 << 16)".
	XN_FLAG_DN_REV := 16r100000	 "(1 << 20)".
	XN_FLAG_FN_MASK := 16r600000	 "(0x3 << 21)".
	XN_FLAG_FN_SN := 0.
	XN_FLAG_FN_LN := 16r200000	 "(1 << 21)".
	XN_FLAG_FN_OID := 16r400000	 "(2 << 21)".
	XN_FLAG_FN_NONE := 16r600000	 "(3 << 21)".
	XN_FLAG_SPC_EQ := 16r800000	 "(1 << 23)".
	XN_FLAG_DUMP_UNKNOWN_FIELDS := 16r1000000	 "(1 << 24)".
	XN_FLAG_FN_ALIGN := 16r2000000	 "(1 << 25)".
	XN_FLAG_RFC2253 := 16r1110317	 "(ASN1_STRFLGS_RFC2253 | \
                        XN_FLAG_SEP_COMMA_PLUS | \
                        XN_FLAG_DN_REV | \
                        XN_FLAG_FN_SN | \
                        XN_FLAG_DUMP_UNKNOWN_FIELDS)".
	XN_FLAG_ONELINE := 16r82031F	 "(ASN1_STRFLGS_RFC2253 | \
                        ASN1_STRFLGS_ESC_QUOTE | \
                        XN_FLAG_SEP_CPLUS_SPC | \
                        XN_FLAG_SPC_EQ | \
                        XN_FLAG_FN_SN)".
	XN_FLAG_MULTILINE := 16r2A40006	 "(ASN1_STRFLGS_ESC_CTRL | \
                        ASN1_STRFLGS_ESC_MSB | \
                        XN_FLAG_SEP_MULTILINE | \
                        XN_FLAG_SPC_EQ | \
                        XN_FLAG_FN_LN | \
                        XN_FLAG_FN_ALIGN)".
	X509_EXT_PACK_UNKNOWN := 1.
	X509_EXT_PACK_STRING := 2.
	X509_VERSION_1 := 0.
	X509_VERSION_2 := 1.
	X509_VERSION_3 := 2.
	X509_REQ_VERSION_1 := 0.
	X509_CRL_VERSION_1 := 0.
	X509_CRL_VERSION_2 := 1.
	X509_ADD_FLAG_DEFAULT := 0.
	X509_ADD_FLAG_UP_REF := 16r1.
	X509_ADD_FLAG_PREPEND := 16r2.
	X509_ADD_FLAG_NO_DUP := 16r4.
	X509_ADD_FLAG_NO_SS := 16r8
]
