Class {
	#name : 'SSLConstantsEngineerr',
	#superclass : 'SharedPool',
	#classVars : [
		'ENGINE_R_ALREADY_LOADED',
		'ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER',
		'ENGINE_R_CMD_NOT_EXECUTABLE',
		'ENGINE_R_COMMAND_TAKES_INPUT',
		'ENGINE_R_COMMAND_TAKES_NO_INPUT',
		'ENGINE_R_CONFLICTING_ENGINE_ID',
		'ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED',
		'ENGINE_R_DSO_FAILURE',
		'ENGINE_R_DSO_NOT_FOUND',
		'ENGINE_R_ENGINES_SECTION_ERROR',
		'ENGINE_R_ENGINE_CONFIGURATION_ERROR',
		'ENGINE_R_ENGINE_IS_NOT_IN_LIST',
		'ENGINE_R_ENGINE_SECTION_ERROR',
		'ENGINE_R_FAILED_LOADING_PRIVATE_KEY',
		'ENGINE_R_FAILED_LOADING_PUBLIC_KEY',
		'ENGINE_R_FINISH_FAILED',
		'ENGINE_R_ID_OR_NAME_MISSING',
		'ENGINE_R_INIT_FAILED',
		'ENGINE_R_INTERNAL_LIST_ERROR',
		'ENGINE_R_INVALID_ARGUMENT',
		'ENGINE_R_INVALID_CMD_NAME',
		'ENGINE_R_INVALID_CMD_NUMBER',
		'ENGINE_R_INVALID_INIT_VALUE',
		'ENGINE_R_INVALID_STRING',
		'ENGINE_R_NOT_INITIALISED',
		'ENGINE_R_NOT_LOADED',
		'ENGINE_R_NO_CONTROL_FUNCTION',
		'ENGINE_R_NO_INDEX',
		'ENGINE_R_NO_LOAD_FUNCTION',
		'ENGINE_R_NO_REFERENCE',
		'ENGINE_R_NO_SUCH_ENGINE',
		'ENGINE_R_UNIMPLEMENTED_CIPHER',
		'ENGINE_R_UNIMPLEMENTED_DIGEST',
		'ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD',
		'ENGINE_R_VERSION_INCOMPATIBILITY'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ALREADY_LOADED [

	^ ENGINE_R_ALREADY_LOADED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER [

	^ ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_CMD_NOT_EXECUTABLE [

	^ ENGINE_R_CMD_NOT_EXECUTABLE
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_COMMAND_TAKES_INPUT [

	^ ENGINE_R_COMMAND_TAKES_INPUT
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_COMMAND_TAKES_NO_INPUT [

	^ ENGINE_R_COMMAND_TAKES_NO_INPUT
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_CONFLICTING_ENGINE_ID [

	^ ENGINE_R_CONFLICTING_ENGINE_ID
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED [

	^ ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_DSO_FAILURE [

	^ ENGINE_R_DSO_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_DSO_NOT_FOUND [

	^ ENGINE_R_DSO_NOT_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ENGINES_SECTION_ERROR [

	^ ENGINE_R_ENGINES_SECTION_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ENGINE_CONFIGURATION_ERROR [

	^ ENGINE_R_ENGINE_CONFIGURATION_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ENGINE_IS_NOT_IN_LIST [

	^ ENGINE_R_ENGINE_IS_NOT_IN_LIST
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ENGINE_SECTION_ERROR [

	^ ENGINE_R_ENGINE_SECTION_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_FAILED_LOADING_PRIVATE_KEY [

	^ ENGINE_R_FAILED_LOADING_PRIVATE_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_FAILED_LOADING_PUBLIC_KEY [

	^ ENGINE_R_FAILED_LOADING_PUBLIC_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_FINISH_FAILED [

	^ ENGINE_R_FINISH_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_ID_OR_NAME_MISSING [

	^ ENGINE_R_ID_OR_NAME_MISSING
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INIT_FAILED [

	^ ENGINE_R_INIT_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INTERNAL_LIST_ERROR [

	^ ENGINE_R_INTERNAL_LIST_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INVALID_ARGUMENT [

	^ ENGINE_R_INVALID_ARGUMENT
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INVALID_CMD_NAME [

	^ ENGINE_R_INVALID_CMD_NAME
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INVALID_CMD_NUMBER [

	^ ENGINE_R_INVALID_CMD_NUMBER
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INVALID_INIT_VALUE [

	^ ENGINE_R_INVALID_INIT_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_INVALID_STRING [

	^ ENGINE_R_INVALID_STRING
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NOT_INITIALISED [

	^ ENGINE_R_NOT_INITIALISED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NOT_LOADED [

	^ ENGINE_R_NOT_LOADED
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NO_CONTROL_FUNCTION [

	^ ENGINE_R_NO_CONTROL_FUNCTION
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NO_INDEX [

	^ ENGINE_R_NO_INDEX
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NO_LOAD_FUNCTION [

	^ ENGINE_R_NO_LOAD_FUNCTION
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NO_REFERENCE [

	^ ENGINE_R_NO_REFERENCE
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_NO_SUCH_ENGINE [

	^ ENGINE_R_NO_SUCH_ENGINE
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_UNIMPLEMENTED_CIPHER [

	^ ENGINE_R_UNIMPLEMENTED_CIPHER
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_UNIMPLEMENTED_DIGEST [

	^ ENGINE_R_UNIMPLEMENTED_DIGEST
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD [

	^ ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD
]

{ #category : 'accessing - constants' }
SSLConstantsEngineerr class >> ENGINE_R_VERSION_INCOMPATIBILITY [

	^ ENGINE_R_VERSION_INCOMPATIBILITY
]

{ #category : 'class initialization' }
SSLConstantsEngineerr class >> initialize [

	ENGINE_R_ALREADY_LOADED := 16r64.
	ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER := 16r85.
	ENGINE_R_CMD_NOT_EXECUTABLE := 16r86.
	ENGINE_R_COMMAND_TAKES_INPUT := 16r87.
	ENGINE_R_COMMAND_TAKES_NO_INPUT := 16r88.
	ENGINE_R_CONFLICTING_ENGINE_ID := 16r67.
	ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED := 16r77.
	ENGINE_R_DSO_FAILURE := 16r68.
	ENGINE_R_DSO_NOT_FOUND := 16r84.
	ENGINE_R_ENGINES_SECTION_ERROR := 16r94.
	ENGINE_R_ENGINE_CONFIGURATION_ERROR := 16r66.
	ENGINE_R_ENGINE_IS_NOT_IN_LIST := 16r69.
	ENGINE_R_ENGINE_SECTION_ERROR := 16r95.
	ENGINE_R_FAILED_LOADING_PRIVATE_KEY := 16r80.
	ENGINE_R_FAILED_LOADING_PUBLIC_KEY := 16r81.
	ENGINE_R_FINISH_FAILED := 16r6A.
	ENGINE_R_ID_OR_NAME_MISSING := 16r6C.
	ENGINE_R_INIT_FAILED := 16r6D.
	ENGINE_R_INTERNAL_LIST_ERROR := 16r6E.
	ENGINE_R_INVALID_ARGUMENT := 16r8F.
	ENGINE_R_INVALID_CMD_NAME := 16r89.
	ENGINE_R_INVALID_CMD_NUMBER := 16r8A.
	ENGINE_R_INVALID_INIT_VALUE := 16r97.
	ENGINE_R_INVALID_STRING := 16r96.
	ENGINE_R_NOT_INITIALISED := 16r75.
	ENGINE_R_NOT_LOADED := 16r70.
	ENGINE_R_NO_CONTROL_FUNCTION := 16r78.
	ENGINE_R_NO_INDEX := 16r90.
	ENGINE_R_NO_LOAD_FUNCTION := 16r7D.
	ENGINE_R_NO_REFERENCE := 16r82.
	ENGINE_R_NO_SUCH_ENGINE := 16r74.
	ENGINE_R_UNIMPLEMENTED_CIPHER := 16r92.
	ENGINE_R_UNIMPLEMENTED_DIGEST := 16r93.
	ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD := 16r65.
	ENGINE_R_VERSION_INCOMPATIBILITY := 16r91
]
