Class {
	#name : 'SSLConstantsX509err',
	#superclass : 'SharedPool',
	#classVars : [
		'X509_R_AKID_MISMATCH',
		'X509_R_BAD_SELECTOR',
		'X509_R_BAD_X509_FILETYPE',
		'X509_R_BASE64_DECODE_ERROR',
		'X509_R_CANT_CHECK_DH_KEY',
		'X509_R_CERTIFICATE_VERIFICATION_FAILED',
		'X509_R_CERT_ALREADY_IN_HASH_TABLE',
		'X509_R_CRL_ALREADY_DELTA',
		'X509_R_CRL_VERIFY_FAILURE',
		'X509_R_DUPLICATE_ATTRIBUTE',
		'X509_R_ERROR_GETTING_MD_BY_NID',
		'X509_R_ERROR_USING_SIGINF_SET',
		'X509_R_IDP_MISMATCH',
		'X509_R_INVALID_ATTRIBUTES',
		'X509_R_INVALID_DIRECTORY',
		'X509_R_INVALID_DISTPOINT',
		'X509_R_INVALID_FIELD_NAME',
		'X509_R_INVALID_TRUST',
		'X509_R_ISSUER_MISMATCH',
		'X509_R_KEY_TYPE_MISMATCH',
		'X509_R_KEY_VALUES_MISMATCH',
		'X509_R_LOADING_CERT_DIR',
		'X509_R_LOADING_DEFAULTS',
		'X509_R_METHOD_NOT_SUPPORTED',
		'X509_R_NAME_TOO_LONG',
		'X509_R_NEWER_CRL_NOT_NEWER',
		'X509_R_NO_CERTIFICATE_FOUND',
		'X509_R_NO_CERTIFICATE_OR_CRL_FOUND',
		'X509_R_NO_CERT_SET_FOR_US_TO_VERIFY',
		'X509_R_NO_CRL_FOUND',
		'X509_R_NO_CRL_NUMBER',
		'X509_R_PUBLIC_KEY_DECODE_ERROR',
		'X509_R_PUBLIC_KEY_ENCODE_ERROR',
		'X509_R_SHOULD_RETRY',
		'X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN',
		'X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY',
		'X509_R_UNKNOWN_KEY_TYPE',
		'X509_R_UNKNOWN_NID',
		'X509_R_UNKNOWN_PURPOSE_ID',
		'X509_R_UNKNOWN_SIGID_ALGS',
		'X509_R_UNKNOWN_TRUST_ID',
		'X509_R_UNSUPPORTED_ALGORITHM',
		'X509_R_UNSUPPORTED_VERSION',
		'X509_R_WRONG_LOOKUP_TYPE',
		'X509_R_WRONG_TYPE'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_AKID_MISMATCH [

	^ X509_R_AKID_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_BAD_SELECTOR [

	^ X509_R_BAD_SELECTOR
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_BAD_X509_FILETYPE [

	^ X509_R_BAD_X509_FILETYPE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_BASE64_DECODE_ERROR [

	^ X509_R_BASE64_DECODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_CANT_CHECK_DH_KEY [

	^ X509_R_CANT_CHECK_DH_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_CERTIFICATE_VERIFICATION_FAILED [

	^ X509_R_CERTIFICATE_VERIFICATION_FAILED
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_CERT_ALREADY_IN_HASH_TABLE [

	^ X509_R_CERT_ALREADY_IN_HASH_TABLE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_CRL_ALREADY_DELTA [

	^ X509_R_CRL_ALREADY_DELTA
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_CRL_VERIFY_FAILURE [

	^ X509_R_CRL_VERIFY_FAILURE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_DUPLICATE_ATTRIBUTE [

	^ X509_R_DUPLICATE_ATTRIBUTE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_ERROR_GETTING_MD_BY_NID [

	^ X509_R_ERROR_GETTING_MD_BY_NID
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_ERROR_USING_SIGINF_SET [

	^ X509_R_ERROR_USING_SIGINF_SET
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_IDP_MISMATCH [

	^ X509_R_IDP_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_INVALID_ATTRIBUTES [

	^ X509_R_INVALID_ATTRIBUTES
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_INVALID_DIRECTORY [

	^ X509_R_INVALID_DIRECTORY
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_INVALID_DISTPOINT [

	^ X509_R_INVALID_DISTPOINT
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_INVALID_FIELD_NAME [

	^ X509_R_INVALID_FIELD_NAME
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_INVALID_TRUST [

	^ X509_R_INVALID_TRUST
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_ISSUER_MISMATCH [

	^ X509_R_ISSUER_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_KEY_TYPE_MISMATCH [

	^ X509_R_KEY_TYPE_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_KEY_VALUES_MISMATCH [

	^ X509_R_KEY_VALUES_MISMATCH
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_LOADING_CERT_DIR [

	^ X509_R_LOADING_CERT_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_LOADING_DEFAULTS [

	^ X509_R_LOADING_DEFAULTS
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_METHOD_NOT_SUPPORTED [

	^ X509_R_METHOD_NOT_SUPPORTED
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NAME_TOO_LONG [

	^ X509_R_NAME_TOO_LONG
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NEWER_CRL_NOT_NEWER [

	^ X509_R_NEWER_CRL_NOT_NEWER
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NO_CERTIFICATE_FOUND [

	^ X509_R_NO_CERTIFICATE_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NO_CERTIFICATE_OR_CRL_FOUND [

	^ X509_R_NO_CERTIFICATE_OR_CRL_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NO_CERT_SET_FOR_US_TO_VERIFY [

	^ X509_R_NO_CERT_SET_FOR_US_TO_VERIFY
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NO_CRL_FOUND [

	^ X509_R_NO_CRL_FOUND
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_NO_CRL_NUMBER [

	^ X509_R_NO_CRL_NUMBER
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_PUBLIC_KEY_DECODE_ERROR [

	^ X509_R_PUBLIC_KEY_DECODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_PUBLIC_KEY_ENCODE_ERROR [

	^ X509_R_PUBLIC_KEY_ENCODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_SHOULD_RETRY [

	^ X509_R_SHOULD_RETRY
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN [

	^ X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY [

	^ X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNKNOWN_KEY_TYPE [

	^ X509_R_UNKNOWN_KEY_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNKNOWN_NID [

	^ X509_R_UNKNOWN_NID
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNKNOWN_PURPOSE_ID [

	^ X509_R_UNKNOWN_PURPOSE_ID
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNKNOWN_SIGID_ALGS [

	^ X509_R_UNKNOWN_SIGID_ALGS
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNKNOWN_TRUST_ID [

	^ X509_R_UNKNOWN_TRUST_ID
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNSUPPORTED_ALGORITHM [

	^ X509_R_UNSUPPORTED_ALGORITHM
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_UNSUPPORTED_VERSION [

	^ X509_R_UNSUPPORTED_VERSION
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_WRONG_LOOKUP_TYPE [

	^ X509_R_WRONG_LOOKUP_TYPE
]

{ #category : 'accessing - constants' }
SSLConstantsX509err class >> X509_R_WRONG_TYPE [

	^ X509_R_WRONG_TYPE
]

{ #category : 'class initialization' }
SSLConstantsX509err class >> initialize [

	X509_R_AKID_MISMATCH := 16r6E.
	X509_R_BAD_SELECTOR := 16r85.
	X509_R_BAD_X509_FILETYPE := 16r64.
	X509_R_BASE64_DECODE_ERROR := 16r76.
	X509_R_CANT_CHECK_DH_KEY := 16r72.
	X509_R_CERTIFICATE_VERIFICATION_FAILED := 16r8B.
	X509_R_CERT_ALREADY_IN_HASH_TABLE := 16r65.
	X509_R_CRL_ALREADY_DELTA := 16r7F.
	X509_R_CRL_VERIFY_FAILURE := 16r83.
	X509_R_DUPLICATE_ATTRIBUTE := 16r8C.
	X509_R_ERROR_GETTING_MD_BY_NID := 16r8D.
	X509_R_ERROR_USING_SIGINF_SET := 16r8E.
	X509_R_IDP_MISMATCH := 16r80.
	X509_R_INVALID_ATTRIBUTES := 16r8A.
	X509_R_INVALID_DIRECTORY := 16r71.
	X509_R_INVALID_DISTPOINT := 16r8F.
	X509_R_INVALID_FIELD_NAME := 16r77.
	X509_R_INVALID_TRUST := 16r7B.
	X509_R_ISSUER_MISMATCH := 16r81.
	X509_R_KEY_TYPE_MISMATCH := 16r73.
	X509_R_KEY_VALUES_MISMATCH := 16r74.
	X509_R_LOADING_CERT_DIR := 16r67.
	X509_R_LOADING_DEFAULTS := 16r68.
	X509_R_METHOD_NOT_SUPPORTED := 16r7C.
	X509_R_NAME_TOO_LONG := 16r86.
	X509_R_NEWER_CRL_NOT_NEWER := 16r84.
	X509_R_NO_CERTIFICATE_FOUND := 16r87.
	X509_R_NO_CERTIFICATE_OR_CRL_FOUND := 16r88.
	X509_R_NO_CERT_SET_FOR_US_TO_VERIFY := 16r69.
	X509_R_NO_CRL_FOUND := 16r89.
	X509_R_NO_CRL_NUMBER := 16r82.
	X509_R_PUBLIC_KEY_DECODE_ERROR := 16r7D.
	X509_R_PUBLIC_KEY_ENCODE_ERROR := 16r7E.
	X509_R_SHOULD_RETRY := 16r6A.
	X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN := 16r6B.
	X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY := 16r6C.
	X509_R_UNKNOWN_KEY_TYPE := 16r75.
	X509_R_UNKNOWN_NID := 16r6D.
	X509_R_UNKNOWN_PURPOSE_ID := 16r79.
	X509_R_UNKNOWN_SIGID_ALGS := 16r90.
	X509_R_UNKNOWN_TRUST_ID := 16r78.
	X509_R_UNSUPPORTED_ALGORITHM := 16r6F.
	X509_R_UNSUPPORTED_VERSION := 16r91.
	X509_R_WRONG_LOOKUP_TYPE := 16r70.
	X509_R_WRONG_TYPE := 16r7A
]
