Class {
	#name : 'SSLConstantsCrypto',
	#superclass : 'SharedPool',
	#classVars : [
		'CRYPTO_EX_INDEX_APP',
		'CRYPTO_EX_INDEX_BIO',
		'CRYPTO_EX_INDEX_DH',
		'CRYPTO_EX_INDEX_DRBG',
		'CRYPTO_EX_INDEX_DSA',
		'CRYPTO_EX_INDEX_EC_KEY',
		'CRYPTO_EX_INDEX_ENGINE',
		'CRYPTO_EX_INDEX_EVP_PKEY',
		'CRYPTO_EX_INDEX_OSSL_LIB_CTX',
		'CRYPTO_EX_INDEX_RAND_DRBG',
		'CRYPTO_EX_INDEX_RSA',
		'CRYPTO_EX_INDEX_SSL',
		'CRYPTO_EX_INDEX_SSL_CTX',
		'CRYPTO_EX_INDEX_SSL_SESSION',
		'CRYPTO_EX_INDEX_UI',
		'CRYPTO_EX_INDEX_UI_METHOD',
		'CRYPTO_EX_INDEX_X509',
		'CRYPTO_EX_INDEX_X509_STORE',
		'CRYPTO_EX_INDEX_X509_STORE_CTX',
		'CRYPTO_EX_INDEX__COUNT',
		'CRYPTO_LOCK',
		'CRYPTO_ONCE_STATIC_INIT',
		'CRYPTO_READ',
		'CRYPTO_UNLOCK',
		'CRYPTO_WRITE',
		'OPENSSL_BUILT_ON',
		'OPENSSL_CFLAGS',
		'OPENSSL_CPU_INFO',
		'OPENSSL_DIR',
		'OPENSSL_ENGINES_DIR',
		'OPENSSL_FULL_VERSION_STRING',
		'OPENSSL_INFO_CONFIG_DIR',
		'OPENSSL_INFO_CPU_SETTINGS',
		'OPENSSL_INFO_DIR_FILENAME_SEPARATOR',
		'OPENSSL_INFO_DSO_EXTENSION',
		'OPENSSL_INFO_ENGINES_DIR',
		'OPENSSL_INFO_LIST_SEPARATOR',
		'OPENSSL_INFO_MODULES_DIR',
		'OPENSSL_INFO_SEED_SOURCE',
		'OPENSSL_INFO_WINDOWS_CONTEXT',
		'OPENSSL_INIT_ADD_ALL_CIPHERS',
		'OPENSSL_INIT_ADD_ALL_DIGESTS',
		'OPENSSL_INIT_ASYNC',
		'OPENSSL_INIT_ATFORK',
		'OPENSSL_INIT_ENGINE_AFALG',
		'OPENSSL_INIT_ENGINE_ALL_BUILTIN',
		'OPENSSL_INIT_ENGINE_CAPI',
		'OPENSSL_INIT_ENGINE_CRYPTODEV',
		'OPENSSL_INIT_ENGINE_DYNAMIC',
		'OPENSSL_INIT_ENGINE_OPENSSL',
		'OPENSSL_INIT_ENGINE_PADLOCK',
		'OPENSSL_INIT_ENGINE_RDRAND',
		'OPENSSL_INIT_LOAD_CONFIG',
		'OPENSSL_INIT_LOAD_CRYPTO_STRINGS',
		'OPENSSL_INIT_NO_ADD_ALL_CIPHERS',
		'OPENSSL_INIT_NO_ADD_ALL_DIGESTS',
		'OPENSSL_INIT_NO_ATEXIT',
		'OPENSSL_INIT_NO_LOAD_CONFIG',
		'OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS',
		'OPENSSL_MODULES_DIR',
		'OPENSSL_PLATFORM',
		'OPENSSL_VERSION',
		'OPENSSL_VERSION_STRING',
		'OPENSSL_WINCTX',
		'SSLEAY_BUILT_ON',
		'SSLEAY_CFLAGS',
		'SSLEAY_DIR',
		'SSLEAY_PLATFORM',
		'SSLEAY_VERSION',
		'SSLEAY_VERSION_NUMBER'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_APP [

	^ CRYPTO_EX_INDEX_APP
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_BIO [

	^ CRYPTO_EX_INDEX_BIO
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_DH [

	^ CRYPTO_EX_INDEX_DH
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_DRBG [

	^ CRYPTO_EX_INDEX_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_DSA [

	^ CRYPTO_EX_INDEX_DSA
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_EC_KEY [

	^ CRYPTO_EX_INDEX_EC_KEY
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_ENGINE [

	^ CRYPTO_EX_INDEX_ENGINE
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_EVP_PKEY [

	^ CRYPTO_EX_INDEX_EVP_PKEY
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_OSSL_LIB_CTX [

	^ CRYPTO_EX_INDEX_OSSL_LIB_CTX
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_RAND_DRBG [

	^ CRYPTO_EX_INDEX_RAND_DRBG
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_RSA [

	^ CRYPTO_EX_INDEX_RSA
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_SSL [

	^ CRYPTO_EX_INDEX_SSL
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_SSL_CTX [

	^ CRYPTO_EX_INDEX_SSL_CTX
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_SSL_SESSION [

	^ CRYPTO_EX_INDEX_SSL_SESSION
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_UI [

	^ CRYPTO_EX_INDEX_UI
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_UI_METHOD [

	^ CRYPTO_EX_INDEX_UI_METHOD
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_X509 [

	^ CRYPTO_EX_INDEX_X509
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_X509_STORE [

	^ CRYPTO_EX_INDEX_X509_STORE
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX_X509_STORE_CTX [

	^ CRYPTO_EX_INDEX_X509_STORE_CTX
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_EX_INDEX__COUNT [

	^ CRYPTO_EX_INDEX__COUNT
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_LOCK [

	^ CRYPTO_LOCK
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_ONCE_STATIC_INIT [

	^ CRYPTO_ONCE_STATIC_INIT
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_READ [

	^ CRYPTO_READ
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_UNLOCK [

	^ CRYPTO_UNLOCK
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> CRYPTO_WRITE [

	^ CRYPTO_WRITE
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_BUILT_ON [

	^ OPENSSL_BUILT_ON
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_CFLAGS [

	^ OPENSSL_CFLAGS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_CPU_INFO [

	^ OPENSSL_CPU_INFO
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_DIR [

	^ OPENSSL_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_ENGINES_DIR [

	^ OPENSSL_ENGINES_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_FULL_VERSION_STRING [

	^ OPENSSL_FULL_VERSION_STRING
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_CONFIG_DIR [

	^ OPENSSL_INFO_CONFIG_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_CPU_SETTINGS [

	^ OPENSSL_INFO_CPU_SETTINGS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_DIR_FILENAME_SEPARATOR [

	^ OPENSSL_INFO_DIR_FILENAME_SEPARATOR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_DSO_EXTENSION [

	^ OPENSSL_INFO_DSO_EXTENSION
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_ENGINES_DIR [

	^ OPENSSL_INFO_ENGINES_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_LIST_SEPARATOR [

	^ OPENSSL_INFO_LIST_SEPARATOR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_MODULES_DIR [

	^ OPENSSL_INFO_MODULES_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_SEED_SOURCE [

	^ OPENSSL_INFO_SEED_SOURCE
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INFO_WINDOWS_CONTEXT [

	^ OPENSSL_INFO_WINDOWS_CONTEXT
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ADD_ALL_CIPHERS [

	^ OPENSSL_INIT_ADD_ALL_CIPHERS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ADD_ALL_DIGESTS [

	^ OPENSSL_INIT_ADD_ALL_DIGESTS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ASYNC [

	^ OPENSSL_INIT_ASYNC
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ATFORK [

	^ OPENSSL_INIT_ATFORK
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_AFALG [

	^ OPENSSL_INIT_ENGINE_AFALG
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_ALL_BUILTIN [

	^ OPENSSL_INIT_ENGINE_ALL_BUILTIN
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_CAPI [

	^ OPENSSL_INIT_ENGINE_CAPI
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_CRYPTODEV [

	^ OPENSSL_INIT_ENGINE_CRYPTODEV
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_DYNAMIC [

	^ OPENSSL_INIT_ENGINE_DYNAMIC
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_OPENSSL [

	^ OPENSSL_INIT_ENGINE_OPENSSL
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_PADLOCK [

	^ OPENSSL_INIT_ENGINE_PADLOCK
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_ENGINE_RDRAND [

	^ OPENSSL_INIT_ENGINE_RDRAND
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_LOAD_CONFIG [

	^ OPENSSL_INIT_LOAD_CONFIG
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_LOAD_CRYPTO_STRINGS [

	^ OPENSSL_INIT_LOAD_CRYPTO_STRINGS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_NO_ADD_ALL_CIPHERS [

	^ OPENSSL_INIT_NO_ADD_ALL_CIPHERS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_NO_ADD_ALL_DIGESTS [

	^ OPENSSL_INIT_NO_ADD_ALL_DIGESTS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_NO_ATEXIT [

	^ OPENSSL_INIT_NO_ATEXIT
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_NO_LOAD_CONFIG [

	^ OPENSSL_INIT_NO_LOAD_CONFIG
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS [

	^ OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_MODULES_DIR [

	^ OPENSSL_MODULES_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_PLATFORM [

	^ OPENSSL_PLATFORM
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_VERSION [

	^ OPENSSL_VERSION
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_VERSION_STRING [

	^ OPENSSL_VERSION_STRING
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> OPENSSL_WINCTX [

	^ OPENSSL_WINCTX
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_BUILT_ON [

	^ SSLEAY_BUILT_ON
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_CFLAGS [

	^ SSLEAY_CFLAGS
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_DIR [

	^ SSLEAY_DIR
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_PLATFORM [

	^ SSLEAY_PLATFORM
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_VERSION [

	^ SSLEAY_VERSION
]

{ #category : 'accessing - constants' }
SSLConstantsCrypto class >> SSLEAY_VERSION_NUMBER [

	^ SSLEAY_VERSION_NUMBER
]

{ #category : 'class initialization' }
SSLConstantsCrypto class >> initialize [

	SSLEAY_VERSION_NUMBER := 16r30500020	 "OPENSSL_VERSION_NUMBER".
	SSLEAY_VERSION := 0	 "OPENSSL_VERSION".
	SSLEAY_CFLAGS := 1	 "OPENSSL_CFLAGS".
	SSLEAY_BUILT_ON := 2	 "OPENSSL_BUILT_ON".
	SSLEAY_PLATFORM := 3	 "OPENSSL_PLATFORM".
	SSLEAY_DIR := 4	 "OPENSSL_DIR".
	OPENSSL_VERSION := 0.
	OPENSSL_CFLAGS := 1.
	OPENSSL_BUILT_ON := 2.
	OPENSSL_PLATFORM := 3.
	OPENSSL_DIR := 4.
	OPENSSL_ENGINES_DIR := 5.
	OPENSSL_VERSION_STRING := 6.
	OPENSSL_FULL_VERSION_STRING := 7.
	OPENSSL_MODULES_DIR := 8.
	OPENSSL_CPU_INFO := 9.
	OPENSSL_WINCTX := 10.
	OPENSSL_INFO_CONFIG_DIR := 16r3E9.
	OPENSSL_INFO_ENGINES_DIR := 16r3EA.
	OPENSSL_INFO_MODULES_DIR := 16r3EB.
	OPENSSL_INFO_DSO_EXTENSION := 16r3EC.
	OPENSSL_INFO_DIR_FILENAME_SEPARATOR := 16r3ED.
	OPENSSL_INFO_LIST_SEPARATOR := 16r3EE.
	OPENSSL_INFO_SEED_SOURCE := 16r3EF.
	OPENSSL_INFO_CPU_SETTINGS := 16r3F0.
	OPENSSL_INFO_WINDOWS_CONTEXT := 16r3F1.
	CRYPTO_EX_INDEX_SSL := 0.
	CRYPTO_EX_INDEX_SSL_CTX := 1.
	CRYPTO_EX_INDEX_SSL_SESSION := 2.
	CRYPTO_EX_INDEX_X509 := 3.
	CRYPTO_EX_INDEX_X509_STORE := 4.
	CRYPTO_EX_INDEX_X509_STORE_CTX := 5.
	CRYPTO_EX_INDEX_DH := 6.
	CRYPTO_EX_INDEX_DSA := 7.
	CRYPTO_EX_INDEX_EC_KEY := 8.
	CRYPTO_EX_INDEX_RSA := 9.
	CRYPTO_EX_INDEX_ENGINE := 10.
	CRYPTO_EX_INDEX_UI := 11.
	CRYPTO_EX_INDEX_BIO := 12.
	CRYPTO_EX_INDEX_APP := 13.
	CRYPTO_EX_INDEX_UI_METHOD := 14.
	CRYPTO_EX_INDEX_RAND_DRBG := 15.
	CRYPTO_EX_INDEX_DRBG := 15	 "CRYPTO_EX_INDEX_RAND_DRBG".
	CRYPTO_EX_INDEX_OSSL_LIB_CTX := 16r10.
	CRYPTO_EX_INDEX_EVP_PKEY := 16r11.
	CRYPTO_EX_INDEX__COUNT := 16r12.
	CRYPTO_LOCK := 1.
	CRYPTO_UNLOCK := 2.
	CRYPTO_READ := 4.
	CRYPTO_WRITE := 8.
	OPENSSL_INIT_NO_LOAD_CRYPTO_STRINGS := 16r00000001.
	OPENSSL_INIT_LOAD_CRYPTO_STRINGS := 16r00000002.
	OPENSSL_INIT_ADD_ALL_CIPHERS := 16r00000004.
	OPENSSL_INIT_ADD_ALL_DIGESTS := 16r00000008.
	OPENSSL_INIT_NO_ADD_ALL_CIPHERS := 16r00000010.
	OPENSSL_INIT_NO_ADD_ALL_DIGESTS := 16r00000020.
	OPENSSL_INIT_LOAD_CONFIG := 16r00000040.
	OPENSSL_INIT_NO_LOAD_CONFIG := 16r00000080.
	OPENSSL_INIT_ASYNC := 16r00000100.
	OPENSSL_INIT_ENGINE_RDRAND := 16r00000200.
	OPENSSL_INIT_ENGINE_DYNAMIC := 16r00000400.
	OPENSSL_INIT_ENGINE_OPENSSL := 16r00000800.
	OPENSSL_INIT_ENGINE_CRYPTODEV := 16r00001000.
	OPENSSL_INIT_ENGINE_CAPI := 16r00002000.
	OPENSSL_INIT_ENGINE_PADLOCK := 16r00004000.
	OPENSSL_INIT_ENGINE_AFALG := 16r00008000.
	OPENSSL_INIT_ATFORK := 16r00020000.
	OPENSSL_INIT_NO_ATEXIT := 16r00080000.
	OPENSSL_INIT_ENGINE_ALL_BUILTIN := 16r7600	 "\
    (OPENSSL_INIT_ENGINE_RDRAND | OPENSSL_INIT_ENGINE_DYNAMIC \
    | OPENSSL_INIT_ENGINE_CRYPTODEV | OPENSSL_INIT_ENGINE_CAPI | \
    OPENSSL_INIT_ENGINE_PADLOCK)".
	CRYPTO_ONCE_STATIC_INIT := 0	 "PTHREAD_ONCE_INIT"
]
