Class {
	#name : 'SSLConstantsDherr',
	#superclass : 'SharedPool',
	#classVars : [
		'DH_R_BAD_FFC_PARAMETERS',
		'DH_R_BAD_GENERATOR',
		'DH_R_BN_DECODE_ERROR',
		'DH_R_BN_ERROR',
		'DH_R_CHECK_INVALID_J_VALUE',
		'DH_R_CHECK_INVALID_Q_VALUE',
		'DH_R_CHECK_PUBKEY_INVALID',
		'DH_R_CHECK_PUBKEY_TOO_LARGE',
		'DH_R_CHECK_PUBKEY_TOO_SMALL',
		'DH_R_CHECK_P_NOT_PRIME',
		'DH_R_CHECK_P_NOT_SAFE_PRIME',
		'DH_R_CHECK_Q_NOT_PRIME',
		'DH_R_DECODE_ERROR',
		'DH_R_INVALID_PARAMETER_NAME',
		'DH_R_INVALID_PARAMETER_NID',
		'DH_R_INVALID_PUBKEY',
		'DH_R_INVALID_SECRET',
		'DH_R_INVALID_SIZE',
		'DH_R_KDF_PARAMETER_ERROR',
		'DH_R_KEYS_NOT_SET',
		'DH_R_MISSING_PUBKEY',
		'DH_R_MODULUS_TOO_LARGE',
		'DH_R_MODULUS_TOO_SMALL',
		'DH_R_NOT_SUITABLE_GENERATOR',
		'DH_R_NO_PARAMETERS_SET',
		'DH_R_NO_PRIVATE_VALUE',
		'DH_R_PARAMETER_ENCODING_ERROR',
		'DH_R_PEER_KEY_ERROR',
		'DH_R_Q_TOO_LARGE',
		'DH_R_SHARED_INFO_ERROR',
		'DH_R_UNABLE_TO_CHECK_GENERATOR'
	],
	#category : 'LibSsl-Library',
	#package : 'LibSsl',
	#tag : 'Library'
}

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_BAD_FFC_PARAMETERS [

	^ DH_R_BAD_FFC_PARAMETERS
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_BAD_GENERATOR [

	^ DH_R_BAD_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_BN_DECODE_ERROR [

	^ DH_R_BN_DECODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_BN_ERROR [

	^ DH_R_BN_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_INVALID_J_VALUE [

	^ DH_R_CHECK_INVALID_J_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_INVALID_Q_VALUE [

	^ DH_R_CHECK_INVALID_Q_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_PUBKEY_INVALID [

	^ DH_R_CHECK_PUBKEY_INVALID
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_PUBKEY_TOO_LARGE [

	^ DH_R_CHECK_PUBKEY_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_PUBKEY_TOO_SMALL [

	^ DH_R_CHECK_PUBKEY_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_P_NOT_PRIME [

	^ DH_R_CHECK_P_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_P_NOT_SAFE_PRIME [

	^ DH_R_CHECK_P_NOT_SAFE_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_CHECK_Q_NOT_PRIME [

	^ DH_R_CHECK_Q_NOT_PRIME
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_DECODE_ERROR [

	^ DH_R_DECODE_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_INVALID_PARAMETER_NAME [

	^ DH_R_INVALID_PARAMETER_NAME
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_INVALID_PARAMETER_NID [

	^ DH_R_INVALID_PARAMETER_NID
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_INVALID_PUBKEY [

	^ DH_R_INVALID_PUBKEY
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_INVALID_SECRET [

	^ DH_R_INVALID_SECRET
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_INVALID_SIZE [

	^ DH_R_INVALID_SIZE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_KDF_PARAMETER_ERROR [

	^ DH_R_KDF_PARAMETER_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_KEYS_NOT_SET [

	^ DH_R_KEYS_NOT_SET
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_MISSING_PUBKEY [

	^ DH_R_MISSING_PUBKEY
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_MODULUS_TOO_LARGE [

	^ DH_R_MODULUS_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_MODULUS_TOO_SMALL [

	^ DH_R_MODULUS_TOO_SMALL
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_NOT_SUITABLE_GENERATOR [

	^ DH_R_NOT_SUITABLE_GENERATOR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_NO_PARAMETERS_SET [

	^ DH_R_NO_PARAMETERS_SET
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_NO_PRIVATE_VALUE [

	^ DH_R_NO_PRIVATE_VALUE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_PARAMETER_ENCODING_ERROR [

	^ DH_R_PARAMETER_ENCODING_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_PEER_KEY_ERROR [

	^ DH_R_PEER_KEY_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_Q_TOO_LARGE [

	^ DH_R_Q_TOO_LARGE
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_SHARED_INFO_ERROR [

	^ DH_R_SHARED_INFO_ERROR
]

{ #category : 'accessing - constants' }
SSLConstantsDherr class >> DH_R_UNABLE_TO_CHECK_GENERATOR [

	^ DH_R_UNABLE_TO_CHECK_GENERATOR
]

{ #category : 'class initialization' }
SSLConstantsDherr class >> initialize [

	DH_R_BAD_FFC_PARAMETERS := 16r7F.
	DH_R_BAD_GENERATOR := 16r65.
	DH_R_BN_DECODE_ERROR := 16r6D.
	DH_R_BN_ERROR := 16r6A.
	DH_R_CHECK_INVALID_J_VALUE := 16r73.
	DH_R_CHECK_INVALID_Q_VALUE := 16r74.
	DH_R_CHECK_PUBKEY_INVALID := 16r7A.
	DH_R_CHECK_PUBKEY_TOO_LARGE := 16r7B.
	DH_R_CHECK_PUBKEY_TOO_SMALL := 16r7C.
	DH_R_CHECK_P_NOT_PRIME := 16r75.
	DH_R_CHECK_P_NOT_SAFE_PRIME := 16r76.
	DH_R_CHECK_Q_NOT_PRIME := 16r77.
	DH_R_DECODE_ERROR := 16r68.
	DH_R_INVALID_PARAMETER_NAME := 16r6E.
	DH_R_INVALID_PARAMETER_NID := 16r72.
	DH_R_INVALID_PUBKEY := 16r66.
	DH_R_INVALID_SECRET := 16r80.
	DH_R_INVALID_SIZE := 16r81.
	DH_R_KDF_PARAMETER_ERROR := 16r70.
	DH_R_KEYS_NOT_SET := 16r6C.
	DH_R_MISSING_PUBKEY := 16r7D.
	DH_R_MODULUS_TOO_LARGE := 16r67.
	DH_R_MODULUS_TOO_SMALL := 16r7E.
	DH_R_NOT_SUITABLE_GENERATOR := 16r78.
	DH_R_NO_PARAMETERS_SET := 16r6B.
	DH_R_NO_PRIVATE_VALUE := 16r64.
	DH_R_PARAMETER_ENCODING_ERROR := 16r69.
	DH_R_PEER_KEY_ERROR := 16r6F.
	DH_R_Q_TOO_LARGE := 16r82.
	DH_R_SHARED_INFO_ERROR := 16r71.
	DH_R_UNABLE_TO_CHECK_GENERATOR := 16r79
]
